export type PointBreakdown = { batting: number; bowling: number; fielding: number; bonus: number; total: number };
export type PlayerMatchStats = { runs: number; balls: number; fours: number; sixes: number; playerIsBowler: boolean; dismissal?: "none" | "duck" | "golden-duck" | "diamond-duck" | "retired-out" | "retired-hurt"; bowlerWickets: number; nonBowlerWickets: number; ballsBowled: number; maxBalls: number; runsConceded: number; maidens: number; dots: number; catches: number; stumpings: number; runOuts: number; sharedRunOuts: number; playerOfMatch: boolean; winningXI: boolean };
export type ScoringRulesDocument = { batting: { run: number; four_bonus: number; six_bonus: number; run_milestones: Array<[number, number]>; duck_non_bowler: number; golden_or_diamond_duck_non_bowler: number; strike_rate_eligibility: { minimum_balls: number; or_minimum_runs: number }; strike_rate_bands: Array<[number, number]> }; bowling: { dismissed_bowler_wicket: number; dismissed_non_bowler_wicket: number; wicket_milestones: Array<[number, number]>; no_wicket_half_quota: number; no_wicket_full_quota: number; maiden: number; dot_ball: number; economy_minimum_balls: number; economy_bands: Array<[number, number]> }; fielding: { catch: number; stumping: number; run_out: number; shared_run_out: number }; bonus: { player_of_match: number; winning_participant: number } };
export const defaultScoringRules: ScoringRulesDocument = { batting: { run: 1, four_bonus: 1, six_bonus: 2, run_milestones: [[25,2],[50,6],[75,12],[100,20],[125,30],[150,42],[175,56],[200,72],[225,90]], duck_non_bowler: -2, golden_or_diamond_duck_non_bowler: -4, strike_rate_eligibility: { minimum_balls: 10, or_minimum_runs: 20 }, strike_rate_bands: [[0,-12],[25,-8],[50,-4],[75,-2],[90,0],[100,2],[125,4],[150,8],[175,14],[225,22],[275,32],[325,44]] }, bowling: { dismissed_bowler_wicket: 15, dismissed_non_bowler_wicket: 20, wicket_milestones: [[2,2],[3,6],[4,12],[5,20],[6,30],[7,42],[8,56],[9,72],[10,90]], no_wicket_half_quota: -2, no_wicket_full_quota: -4, maiden: 10, dot_ball: 2, economy_minimum_balls: 6, economy_bands: [[0,44],[1,32],[2,22],[3,14],[4,8],[5,4],[6,2],[7,0],[8,-2],[10,-4],[12,-8],[14,-12]] }, fielding: { catch: 10, stumping: 10, run_out: 10, shared_run_out: 8 }, bonus: { player_of_match: 15, winning_participant: 2 } };
const band = (value: number, values: Array<[number, number]>) => { let result = 0; for (const [minimum, points] of values) if (value >= minimum) result = points; return result; };
function components(stats: PlayerMatchStats, rules: ScoringRulesDocument) {
  const strikeRate = stats.balls ? stats.runs * 100 / stats.balls : 0;
  const strikeEligible = stats.balls >= rules.batting.strike_rate_eligibility.minimum_balls || stats.runs >= rules.batting.strike_rate_eligibility.or_minimum_runs;
  const strike = strikeEligible ? band(strikeRate, rules.batting.strike_rate_bands) : 0;
  const dismissal = stats.playerIsBowler ? 0 : stats.dismissal === "golden-duck" || stats.dismissal === "diamond-duck" ? rules.batting.golden_or_diamond_duck_non_bowler : stats.dismissal === "duck" ? rules.batting.duck_non_bowler : 0;
  const wickets = stats.bowlerWickets + stats.nonBowlerWickets;
  const economy = stats.ballsBowled ? stats.runsConceded / (stats.ballsBowled / 6) : 0;
  const economyPoints = stats.ballsBowled >= rules.bowling.economy_minimum_balls ? band(economy, rules.bowling.economy_bands) : 0;
  const noWicket = wickets ? 0 : stats.ballsBowled >= stats.maxBalls ? rules.bowling.no_wicket_full_quota : stats.ballsBowled >= Math.min(stats.maxBalls / 2, 12) ? rules.bowling.no_wicket_half_quota : 0;
  return { strike, dismissal, wickets, economyPoints, noWicket };
}
export function calculatePlayerPoints(stats: PlayerMatchStats, rules = defaultScoringRules): PointBreakdown {
  const c = components(stats, rules);
  const batting = stats.runs * rules.batting.run + stats.fours * rules.batting.four_bonus + stats.sixes * rules.batting.six_bonus + band(stats.runs, rules.batting.run_milestones) + c.strike + c.dismissal;
  const bowling = stats.bowlerWickets * rules.bowling.dismissed_bowler_wicket + stats.nonBowlerWickets * rules.bowling.dismissed_non_bowler_wicket + band(c.wickets, rules.bowling.wicket_milestones) + stats.maidens * rules.bowling.maiden + stats.dots * rules.bowling.dot_ball + c.economyPoints + c.noWicket;
  const fielding = stats.catches * rules.fielding.catch + stats.stumpings * rules.fielding.stumping + stats.runOuts * rules.fielding.run_out + stats.sharedRunOuts * rules.fielding.shared_run_out;
  const bonus = (stats.playerOfMatch ? rules.bonus.player_of_match : 0) + (stats.winningXI ? rules.bonus.winning_participant : 0);
  return { batting, bowling, fielding, bonus, total: batting + bowling + fielding + bonus };
}
export function calculatePointDetails(stats: PlayerMatchStats, rules = defaultScoringRules) { const c = components(stats, rules); return { batting: [["Runs", stats.runs * rules.batting.run], ["Fours", stats.fours * rules.batting.four_bonus], ["Sixes", stats.sixes * rules.batting.six_bonus], ["Run milestone", band(stats.runs, rules.batting.run_milestones)], ["Strike rate", c.strike], ["Dismissal", c.dismissal]] as Array<[string,number]>, bowling: [["Bowler wickets", stats.bowlerWickets * rules.bowling.dismissed_bowler_wicket], ["Non-bowler wickets", stats.nonBowlerWickets * rules.bowling.dismissed_non_bowler_wicket], ["Wicket milestone", band(c.wickets, rules.bowling.wicket_milestones)], ["Maidens", stats.maidens * rules.bowling.maiden], ["Dot balls", stats.dots * rules.bowling.dot_ball], ["Economy", c.economyPoints], ["No-wicket adjustment", c.noWicket]] as Array<[string,number]>, fielding: [["Catches", stats.catches * rules.fielding.catch], ["Stumpings", stats.stumpings * rules.fielding.stumping], ["Run-outs", stats.runOuts * rules.fielding.run_out], ["Shared run-outs", stats.sharedRunOuts * rules.fielding.shared_run_out]] as Array<[string,number]>, bonus: [["Player of the Match", stats.playerOfMatch ? rules.bonus.player_of_match : 0], ["Winning team", stats.winningXI ? rules.bonus.winning_participant : 0]] as Array<[string,number]> }; }
export function applyFantasyMarkers(points: PointBreakdown, marker: "" | "C" | "VC" | "BAI" | "BOI", captainMultiplier = 2, viceMultiplier = 1.5, impactMultiplier = 2) { if (marker === "C") return points.total * captainMultiplier; if (marker === "VC") return points.total * viceMultiplier; if (marker === "BAI") return points.batting * impactMultiplier; if (marker === "BOI") return points.bowling * impactMultiplier; return points.total; }
export const match1Source = { id: "1527674", teams: "RCB vs SRH", result: "RCB won by 6 wickets", score: "SRH 201/9; RCB 203/4 (15.4 overs)", playerOfMatch: "Jacob Duffy", scorecardUrl: "https://www.cricinfo.com/series/ipl-2026-1510719/royal-challengers-bengaluru-vs-sunrisers-hyderabad-1st-match-1527674/full-scorecard" } as const;
export const match2Source = { id: "1527675", teams: "KKR vs MI", result: "MI won by 6 wickets", score: "KKR 220/4; MI 224/4 (19.1 overs)", playerOfMatch: "Shardul Thakur", scorecardUrl: "https://www.cricinfo.com/series/ipl-2026-1510719/mumbai-indians-vs-kolkata-knight-riders-2nd-match-1527675/full-scorecard" } as const;
