-- DEVELOPMENT / VOLUME TEST DATA
-- Source: Google Sheet League tab and score-template tabs M1-M10.
-- Scorecards cross-checked with Cricbuzz / ESPNcricinfo.
-- This script intentionally replaces match-derived data for IPL 2026. It first
-- records a JSON backup, then imports 9 owners x 10 matches and schedules M11.
-- The supplied workbook contains withdrawn/superseded roster entries; its Squad
-- tab is authoritative for this isolated volume test. Re-running the script
-- creates another backup and replaces the same test state.
-- Source extraction notes: each League match block is 50 rows and each owner
-- occupies a 14-column block. Two blank-marker rows in the source carry the
-- prior submitted C/VC/impact choices: Mansur M3 and Saravana M7.
begin;
set local statement_timeout = '120s';
set local lock_timeout = '15s';

create temporary table vt_lineups(owner_name text,match_number int,captain_name text,vice_captain_name text,impact_name text,impact_type text,booster_code text,sheet_transfers int) on commit drop;
create temporary table vt_sheet_roster(player_name text,team_code text,role_code text,selection_cost numeric,owner_name text,bid_cost numeric,withdrawn boolean) on commit drop;
insert into vt_sheet_roster values
('Anshul Kamboj','CSK','AL',7,'Bala',3,false),
('Ayush Mhatre','CSK','BA',7,'Bala',3.5,true),
('Jamie Overton','CSK','AL',8,'Jeba',2,true),
('Kartik Sharma','CSK','WK',7,'Pandiyan',5.5,false),
('Khaleel Ahmed','CSK','BO',8,'Pandiyan',4,true),
('Matt Henry','CSK','BO',8,'Tamil',2,false),
('Matthew Short','CSK','BA',8,null,null,false),
('Noor Ahmad','CSK','BO',8,'Saravana',7,false),
('Prashant Veer','CSK','AL',7,'Pandiyan',3,false),
('Rahul Chahar','CSK','BO',8,'Mansur',3,false),
('Ruturaj Gaikwad','CSK','BA',9,'Jeba',14,false),
('Sanju Samson','CSK','WK',8.5,'Murali',11,false),
('Sarfaraz Khan','CSK','BA',7,'Tamil',1,false),
('Shivam Dube','CSK','AL',8.5,'Bala',7.5,false),
('Abishek Porel','DC','WK',7,'Sashi',3,false),
('Ashutosh Sharma','DC','AL',7.5,'Sashi',3,false),
('Axar Patel','DC','AL',8.5,'Sashi',12,false),
('David Miller','DC','BA',9,'Bala',6,false),
('Dushmantha Chameera','DC','BO',8,'Jeba',2.5,false),
('KL Rahul','DC','WK',9,'Tamil',13,false),
('Kuldeep Yadav','DC','BO',8.5,'Murali',7,false),
('Lungi Ngidi','DC','BO',8,'Pandiyan',4.5,false),
('Mitchell Starc','DC','BO',8.5,'Saravana',6.5,false),
('Mukesh Kumar','DC','BO',8,'Bala',4,false),
('Nitish Rana','DC','BA',8,'Pandiyan',4,false),
('Pathum Nissanka','DC','BA',8,'Bala',4,false),
('Sameer Rizvi','DC','BA',7,'Murali',1,false),
('T Natarajan','DC','BO',8,'Jeba',2,false),
('Tristan Stubbs','DC','BA',8,'Jeba',4,false),
('Vipraj Nigam','DC','BO',7.5,'Pandiyan',4.5,false),
('Arshad Khan','GT','BO',7,'Bala',1,false),
('Ashok Sharma','GT','BO',7,'Jeba',1,false),
('Glenn Phillips','GT','AL',8,'Murali',2.5,false),
('Ishant Sharma','GT','BO',8,'Sashi',2,false),
('Jason Holder','GT','AL',8.5,'Saravana',6,false),
('Jayant Yadav','GT','BO',8,'Tamil',2,false),
('Jos Buttler','GT','WK',9.5,'Johny',12,false),
('Kagiso Rabada','GT','BO',8.5,'Sashi',5.5,false),
('Kumar Kushagra','GT','WK',7,'Pandiyan',1,false),
('M Shahrukh Khan','GT','BA',8,'Pandiyan',4,false),
('Mohammed Siraj','GT','BO',8.5,'Mansur',6,false),
('Prasidh Krishna','GT','BO',8,'Murali',6.5,false),
('Rahul Tewatia','GT','AL',8,'Bala',3.5,false),
('Rashid Khan','GT','AL',9.5,'Sashi',7.5,false),
('Sai Kishore','GT','BO',8,'Jeba',3.5,false),
('Sai Sudharsan','GT','BA',8,'Saravana',13,false),
('Shubman Gill','GT','BA',9,'Mansur',15,false),
('Washington Sundar','GT','AL',8,'Pandiyan',3,false),
('Ajinkya Rahane','KKR','BA',8.5,'Saravana',10,false),
('Angkrish Raghuvanshi','KKR','BA',7.5,'Pandiyan',3.5,false),
('Blessing Muzarabani','KKR','BO',7,null,null,false),
('Cameron Green','KKR','AL',8.5,'Mansur',9.5,false),
('Finn Allen','KKR','BA',8,null,null,false),
('Kartik Tyagi','KKR','BO',7,'Jeba',1,false),
('Matheesha Pathirana','KKR','BO',8,'Sashi',2,false),
('Ramandeep Singh','KKR','BA',7.5,'Sashi',3,false),
('Rinku Singh','KKR','BA',8.5,'Murali',7,false),
('Saurabh Dubey','KKR','BO',7,'Bala',null,false),
('Sunil Narine','KKR','AL',8.5,'Jeba',11,false),
('Vaibhav Arora','KKR','BO',7.5,'Bala',2.5,false),
('Varun Chakravarthy','KKR','BO',8,'Pandiyan',6.5,false),
('Abdul Samad','LSG','BA',7.5,'Sashi',4.5,false),
('Aiden Markram','LSG','BA',9,'Jeba',14,false),
('Anrich Nortje','LSG','BO',8.5,'Mansur',3.5,false),
('Avesh Khan','LSG','BO',8.5,'Johny',3,false),
('Ayush Badoni','LSG','BA',7.5,'Bala',7,false),
('Digvesh Rathi','LSG','BO',7.5,'Saravana',4,false),
('Mayank Yadav','LSG','BO',7,'Murali',1.5,false),
('Mitchell Marsh','LSG','AL',9,'Pandiyan',13,false),
('Mohammed Shami','LSG','BO',8,'Jeba',4.5,false),
('Mohsin Khan','LSG','BO',7.5,'Pandiyan',1,false),
('Mukul Choudhary','LSG','BA',7,'Pandiyan',1,false),
('Naman Tiwari','LSG','BO',7,'Jeba',1,false),
('Nicholas Pooran','LSG','WK',9.5,'Murali',12,false),
('Prince Yadav','LSG','BO',7,'Sashi',1,false),
('Rishabh Pant','LSG','WK',9,'Mansur',9,false),
('AM Ghazanfar','MI','BO',7,'Sashi',2.5,false),
('Corbin Bosch','MI','AL',7.5,'Johny',2.5,false),
('Deepak Chahar','MI','BO',8.5,'Saravana',5.5,false),
('Hardik Pandya','MI','AL',11,'Saravana',13,false),
('Jasprit Bumrah','MI','BO',10,'Mansur',11,false),
('Mayank Markande','MI','BO',7.5,'Tamil',1,false),
('Mitchell Santner','MI','AL',9,'Bala',4,true),
('Naman Dhir','MI','BA',7,'Sashi',3,false),
('Rohit Sharma','MI','BA',9,'Tamil',8.5,false),
('Ryan Rickelton','MI','WK',8,'Jeba',5.5,false),
('Shardul Thakur','MI','BO',8,'Pandiyan',2.5,false),
('Sherfane Rutherford','MI','BA',8,'Tamil',2,false),
('Suryakumar Yadav','MI','BA',10,'Murali',16,false),
('Tilak Varma','MI','AL',8.5,'Sashi',8.5,false),
('Trent Boult','MI','BO',9,'Bala',8,false),
('Cooper Connolly','PBKS','AL',7,'Tamil',1,false),
('Harpreet Brar','PBKS','BO',8,'Pandiyan',3,false),
('Marco Jansen','PBKS','AL',8.5,'Murali',6.5,false),
('Marcus Stoinis','PBKS','AL',9.5,'Mansur',6,false),
('Nehal Wadhera','PBKS','BA',7.5,'Pandiyan',7.5,false),
('Prabhsimran Singh','PBKS','WK',8,'Saravana',8,false),
('Priyansh Arya','PBKS','BA',7.5,'Sashi',9,false),
('Shashank Singh','PBKS','AL',8,'Sashi',5,false),
('Shreyas Iyer','PBKS','BA',9,'Johny',12,false),
('Vijaykumar Vyshak','PBKS','BO',7.5,'Bala',1,false),
('Xavier Bartlett','PBKS','BO',7,'Jeba',3.5,false),
('Yash Thakur','PBKS','BO',7.5,'Sashi',1,false),
('Yuzvendra Chahal','PBKS','BO',8.5,'Johny',6,false),
('Abhinandan Singh','RCB','BO',7,null,null,false),
('Bhuvneshwar Kumar','RCB','BO',9,'Murali',6,false),
('Devdutt Padikkal','RCB','BA',8,'Saravana',5.5,false),
('Jacob Duffy','RCB','BO',8,'Tamil',2,false),
('Jitesh Sharma','RCB','WK',8.5,'Murali',6.5,false),
('Krunal Pandya','RCB','AL',8.5,'Johny',8,false),
('Mangesh Yadav','RCB','AL',7,'Saravana',1,false),
('Phil Salt','RCB','WK',8.5,'Tamil',11,false),
('Rajat Patidar','RCB','BA',8,'Johny',10,false),
('Rasikh Salam','RCB','BO',7,'Sashi',1.5,false),
('Romario Shepherd','RCB','AL',8,'Bala',4,false),
('Suyash Sharma','RCB','BO',7,'Jeba',1.5,false),
('Tim David','RCB','BA',8.5,'Mansur',6,false),
('Venkatesh Iyer','RCB','AL',8.5,'Sashi',5.5,false),
('Virat Kohli','RCB','BA',9,'Tamil',16,false),
('Dhruv Jurel','RR','WK',8,'Sashi',4,false),
('Jofra Archer','RR','BO',8.5,'Jeba',5.5,false),
('Ravi Bishnoi','RR','BO',8.5,'Mansur',4,false),
('Ravindra Jadeja','RR','AL',9,'Murali',10,false),
('Riyan Parag','RR','BA',8.5,'Tamil',11,false),
('Sandeep Sharma','RR','BO',8.5,'Bala',2.5,false),
('Shimron Hetmyer','RR','BA',8.5,'Mansur',7.5,false),
('Tushar Deshpande','RR','BO',8,'Saravana',2,false),
('Vaibhav Sooryavanshi','RR','BA',8,'Tamil',12,false),
('Vignesh Puthur','RR','BO',7,'Saravana',1.5,false),
('Yashasvi Jaiswal','RR','BA',9,'Johny',12,false),
('Abhishek Sharma','SRH','AL',8.5,'Pandiyan',13,false),
('Aniket Verma','SRH','BA',7.5,'Saravana',2.5,false),
('David Payne','SRH','BO',7,'Tamil',null,false),
('Eshan Malinga','SRH','BO',7,'Sashi',3,false),
('Harshal Patel','SRH','BO',8.5,'Murali',5.5,false),
('Heinrich Klaasen','SRH','WK',8.5,'Jeba',12,false),
('Ishan Kishan','SRH','WK',9,'Bala',14,false),
('Jaydev Unadkat','SRH','BO',8,'Johny',2.5,false),
('Liam Livingstone','SRH','AL',8.5,'Jeba',3,false),
('Nitish Kumar Reddy','SRH','AL',8.5,'Mansur',5,false),
('Salil Arora','SRH','WK',7,'Sashi',4,false),
('Shivang Kumar','SRH','BO',7,null,null,false),
('Travis Head','SRH','BA',9,'Bala',10,false),
('Zeeshan Ansari','SRH','BO',7.5,'Saravana',2.5,false);
insert into vt_lineups values
('Bala',1,'Ishan Kishan','Romario Shepherd','Travis Head','BAI','',3),
('Bala',2,'Angkrish Raghuvanshi','Trent Boult','Tilak Varma','BAI','',3),
('Bala',3,'Shivam Dube','Shimron Hetmyer','Ayush Mhatre','BAI','',4),
('Bala',4,'Shreyas Iyer','Jos Buttler','Vijaykumar Vyshak','BOI','',4),
('Bala',5,'Aiden Markram','Ayush Badoni','Pathum Nissanka','BAI','',5),
('Bala',6,'Ishan Kishan','Travis Head','Finn Allen','BAI','',2),
('Bala',7,'Shivam Dube','Vijaykumar Vyshak','Sanju Samson','BAI','',2),
('Bala',8,'Mitchell Santner','David Miller','Pathum Nissanka','BAI','',2),
('Bala',9,'Dhruv Jurel','Jos Buttler','Sai Sudharsan','BAI','',2),
('Bala',10,'Ishan Kishan','Nicholas Pooran','Travis Head','BAI','',5),
('Jeba',1,'Abhishek Sharma','Phil Salt','Virat Kohli','BAI','2UP',1),
('Jeba',2,'Ryan Rickelton','Sunil Narine','Kartik Tyagi','BOI','',6),
('Jeba',3,'Sanju Samson','Vaibhav Sooryavanshi','Ruturaj Gaikwad','BAI','',3),
('Jeba',4,'Priyansh Arya','Ashok Sharma','Xavier Bartlett','BOI','',9),
('Jeba',5,'Aiden Markram','Tristan Stubbs','Mohammed Shami','BOI','',2),
('Jeba',6,'Finn Allen','Heinrich Klaasen','Abhishek Sharma','BAI','',3),
('Jeba',7,'Sanju Samson','Priyansh Arya','Ruturaj Gaikwad','BAI','',4),
('Jeba',8,'Ryan Rickelton','Tristan Stubbs','T Natarajan','BOI','',8),
('Jeba',9,'Vaibhav Sooryavanshi','Jofra Archer','Yashasvi Jaiswal','BAI','',7),
('Jeba',10,'Aiden Markram','Heinrich Klaasen','Ishan Kishan','BAI','',2),
('Johny',1,'Krunal Pandya','Ishan Kishan','Virat Kohli','BAI','',6),
('Johny',2,'Sunil Narine','Varun Chakravarthy','Rohit Sharma','BAI','',4),
('Johny',3,'Yashasvi Jaiswal','Sanju Samson','Ruturaj Gaikwad','BAI','',6),
('Johny',4,'Jos Buttler','Shreyas Iyer','Yuzvendra Chahal','BOI','',2),
('Johny',5,'KL Rahul','Nicholas Pooran','Avesh Khan','BOI','',9),
('Johny',6,'Ishan Kishan','Abhishek Sharma','Varun Chakravarthy','BOI','',5),
('Johny',7,'Shreyas Iyer','Sanju Samson','Yuzvendra Chahal','BOI','',6),
('Johny',8,'Ryan Rickelton','Corbin Bosch','KL Rahul','BAI','',9),
('Johny',9,'Jos Buttler','Vaibhav Sooryavanshi','Yashasvi Jaiswal','BAI','',5),
('Johny',10,'Abhishek Sharma','Nicholas Pooran','Jaydev Unadkat','BOI','',6),
('Mansur',1,'Tim David','Nitish Kumar Reddy','Phil Salt','BAI','',9),
('Mansur',2,'Cameron Green','Hardik Pandya','Jasprit Bumrah','BOI','',2),
('Mansur',3,'Cameron Green','Hardik Pandya','Jasprit Bumrah','BOI','',9),
('Mansur',4,'Marcus Stoinis','Prabhsimran Singh','Shubman Gill','BAI','',6),
('Mansur',5,'KL Rahul','Rishabh Pant','Anrich Nortje','BOI','',6),
('Mansur',6,'Finn Allen','Ishan Kishan','Cameron Green','BAI','',6),
('Mansur',7,'Marcus Stoinis','Sanju Samson','Shreyas Iyer','BAI','',3),
('Mansur',8,'Rohit Sharma','KL Rahul','Jasprit Bumrah','BOI','',4),
('Mansur',9,'Vaibhav Sooryavanshi','Shimron Hetmyer','Kumar Kushagra','BAI','',6),
('Mansur',10,'Rishabh Pant','Nitish Kumar Reddy','Abhishek Sharma','BAI','',3),
('Murali',1,'Abhishek Sharma','Ishan Kishan','Virat Kohli','BAI','',7),
('Murali',2,'Finn Allen','Rinku Singh','Suryakumar Yadav','BAI','',8),
('Murali',3,'Sanju Samson','Ravindra Jadeja','Yashasvi Jaiswal','BAI','',1),
('Murali',4,'Glenn Phillips','Marco Jansen','Prasidh Krishna','BOI','',1),
('Murali',5,'Nicholas Pooran','Kuldeep Yadav','Pathum Nissanka','BAI','',4),
('Murali',6,'Finn Allen','Rinku Singh','Abhishek Sharma','BAI','',4),
('Murali',7,'Sanju Samson','Marco Jansen','Shreyas Iyer','BAI','',5),
('Murali',8,'Suryakumar Yadav','Kuldeep Yadav','Pathum Nissanka','BAI','',1),
('Murali',9,'Glenn Phillips','Ravindra Jadeja','Prasidh Krishna','BOI','',8),
('Murali',10,'Nicholas Pooran','Abhishek Sharma','Ishan Kishan','BAI','',9),
('Pandiyan',1,'Abhishek Sharma','Nitish Kumar Reddy','Virat Kohli','BAI','',5),
('Pandiyan',2,'Hardik Pandya','Angkrish Raghuvanshi','Rohit Sharma','BAI','',1),
('Pandiyan',3,'Sanju Samson','Matthew Short','Yashasvi Jaiswal','BAI','',7),
('Pandiyan',4,'Shubman Gill','Washington Sundar','Shreyas Iyer','BAI','',5),
('Pandiyan',5,'KL Rahul','Nitish Rana','Mitchell Marsh','BAI','',1),
('Pandiyan',6,'Abhishek Sharma','Angkrish Raghuvanshi','Ishan Kishan','BAI','',1),
('Pandiyan',7,'Sanju Samson','Nehal Wadhera','Khaleel Ahmed','BOI','',8),
('Pandiyan',8,'KL Rahul','Suryakumar Yadav','Lungi Ngidi','BOI','',5),
('Pandiyan',9,'Vaibhav Sooryavanshi','Washington Sundar','Kumar Kushagra','BAI','',9),
('Pandiyan',10,'Abhishek Sharma','Nitish Kumar Reddy','Mitchell Marsh','BAI','2UP',1),
('Saravana',1,'Virat Kohli','Ishan Kishan','Devdutt Padikkal','BAI','',4),
('Saravana',2,'Hardik Pandya','Deepak Chahar','Ajinkya Rahane','BAI','',5),
('Saravana',3,'Ruturaj Gaikwad','Sanju Samson','Yashasvi Jaiswal','BAI','',8),
('Saravana',4,'Sai Sudharsan','Jason Holder','Prabhsimran Singh','BAI','',8),
('Saravana',5,'Axar Patel','Digvesh Rathi','KL Rahul','BAI','',7),
('Saravana',6,'Ajinkya Rahane','Aniket Verma','Ishan Kishan','BAI','',9),
('Saravana',7,'Ajinkya Rahane','Aniket Verma','Ishan Kishan','BAI','',9),
('Saravana',8,'Hardik Pandya','Axar Patel','Deepak Chahar','BOI','',7),
('Saravana',9,'Sai Sudharsan','Yashasvi Jaiswal','Vaibhav Sooryavanshi','BAI','',3),
('Saravana',10,'Ishan Kishan','Aniket Verma','Travis Head','BAI','',8),
('Sashi',1,'Virat Kohli','Abhishek Sharma','Travis Head','BAI','',8),
('Sashi',2,'Tilak Varma','Naman Dhir','Suryakumar Yadav','BAI','',9),
('Sashi',3,'Dhruv Jurel','Sanju Samson','Yashasvi Jaiswal','BAI','',5),
('Sashi',4,'Rashid Khan','Kagiso Rabada','Priyansh Arya','BAI','',7),
('Sashi',5,'Axar Patel','Abdul Samad','Abishek Porel','BAI','',3),
('Sashi',6,'Heinrich Klaasen','Ramandeep Singh','Travis Head','BAI','',7),
('Sashi',7,'Ruturaj Gaikwad','Priyansh Arya','Sanju Samson','BAI','',7),
('Sashi',8,'Axar Patel','Tilak Varma','Suryakumar Yadav','BAI','',3),
('Sashi',9,'Rashid Khan','Dhruv Jurel','Yashasvi Jaiswal','BAI','',1),
('Sashi',10,'Heinrich Klaasen','Abdul Samad','Travis Head','BAI','',4),
('Tamil',1,'Virat Kohli','Phil Salt','Jacob Duffy','BOI','',2),
('Tamil',2,'Rohit Sharma','Sherfane Rutherford','Mayank Markande','BOI','',7),
('Tamil',3,'Riyan Parag','Matt Henry','Vaibhav Sooryavanshi','BAI','',2),
('Tamil',4,'Shubman Gill','Jayant Yadav','Cooper Connolly','BAI','',3),
('Tamil',5,'KL Rahul','Aiden Markram','Mayank Yadav','BOI','',8),
('Tamil',6,'Ishan Kishan','David Payne','Finn Allen','BAI','',8),
('Tamil',7,'Matt Henry','Sarfaraz Khan','Cooper Connolly','BAI','',1),
('Tamil',8,'KL Rahul','Mayank Markande','Rohit Sharma','BAI','',6),
('Tamil',9,'Riyan Parag','Kumar Kushagra','Vaibhav Sooryavanshi','BAI','',4),
('Tamil',10,'Abhishek Sharma','David Payne','Ishan Kishan','BAI','',7);

create temporary table vt_lineup_players(owner_name text,match_number int,slot int,player_name text,team_code text,role text,cost numeric,marker text) on commit drop;
insert into vt_lineup_players values
('Bala',1,1,'Romario Shepherd','RCB','AL',8,'VC'),
('Bala',1,2,'Eshan Malinga','SRH','BO',7,''),
('Bala',1,3,'Hardik Pandya','MI','AL',11,''),
('Bala',1,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',1,5,'Tilak Varma','MI','AL',8.5,''),
('Bala',1,6,'Virat Kohli','RCB','BA',9,''),
('Bala',1,7,'Travis Head','SRH','BA',9,'BAI'),
('Bala',1,8,'Ishan Kishan','SRH','WK',9,'C'),
('Bala',1,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Bala',1,10,'Krunal Pandya','RCB','AL',8.5,''),
('Bala',1,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',2,1,'Vaibhav Arora','KKR','BO',7.5,''),
('Bala',2,2,'Eshan Malinga','SRH','BO',7,''),
('Bala',2,3,'Hardik Pandya','MI','AL',11,''),
('Bala',2,4,'Angkrish Raghuvanshi','KKR','BA',7.5,'C'),
('Bala',2,5,'Tilak Varma','MI','AL',8.5,'BAI'),
('Bala',2,6,'Virat Kohli','RCB','BA',9,''),
('Bala',2,7,'Trent Boult','MI','BO',9,'VC'),
('Bala',2,8,'Ishan Kishan','SRH','WK',9,''),
('Bala',2,9,'Saurabh Dubey','KKR','BO',7,''),
('Bala',2,10,'Finn Allen','KKR','BA',8,''),
('Bala',2,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',3,1,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Bala',3,2,'Sandeep Sharma','RR','BO',8.5,''),
('Bala',3,3,'Anshul Kamboj','CSK','AL',7,''),
('Bala',3,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',3,5,'Shimron Hetmyer','RR','BA',8.5,'VC'),
('Bala',3,6,'Virat Kohli','RCB','BA',9,''),
('Bala',3,7,'Shivam Dube','CSK','AL',8.5,'C'),
('Bala',3,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',3,9,'Ayush Mhatre','CSK','BA',7,'BAI'),
('Bala',3,10,'Finn Allen','KKR','BA',8,''),
('Bala',3,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',4,1,'Shreyas Iyer','PBKS','BA',9,'C'),
('Bala',4,2,'Sandeep Sharma','RR','BO',8.5,''),
('Bala',4,3,'Vijaykumar Vyshak','PBKS','BO',7.5,'BOI'),
('Bala',4,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',4,5,'Jos Buttler','GT','WK',9.5,'VC'),
('Bala',4,6,'Virat Kohli','RCB','BA',9,''),
('Bala',4,7,'Rahul Tewatia','GT','AL',8,''),
('Bala',4,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',4,9,'Arshad Khan','GT','BO',7,''),
('Bala',4,10,'Finn Allen','KKR','BA',8,''),
('Bala',4,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',5,1,'Shreyas Iyer','PBKS','BA',9,''),
('Bala',5,2,'David Miller','DC','BA',9,''),
('Bala',5,3,'Pathum Nissanka','DC','BA',8,'BAI'),
('Bala',5,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',5,5,'Aiden Markram','LSG','BA',9,'C'),
('Bala',5,6,'Mukesh Kumar','DC','BO',8,''),
('Bala',5,7,'Ayush Badoni','LSG','BA',7.5,'VC'),
('Bala',5,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',5,9,'Axar Patel','DC','AL',8.5,''),
('Bala',5,10,'Finn Allen','KKR','BA',8,''),
('Bala',5,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',6,1,'Shreyas Iyer','PBKS','BA',9,''),
('Bala',6,2,'Travis Head','SRH','BA',9,'VC'),
('Bala',6,3,'Ishan Kishan','SRH','WK',9,'C'),
('Bala',6,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',6,5,'Aiden Markram','LSG','BA',9,''),
('Bala',6,6,'Vaibhav Arora','KKR','BO',7.5,''),
('Bala',6,7,'Aniket Verma','SRH','BA',7.5,''),
('Bala',6,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',6,9,'Axar Patel','DC','AL',8.5,''),
('Bala',6,10,'Finn Allen','KKR','BA',8,'BAI'),
('Bala',6,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',7,1,'Shreyas Iyer','PBKS','BA',9,''),
('Bala',7,2,'Shivam Dube','CSK','AL',8.5,'C'),
('Bala',7,3,'Ayush Mhatre','CSK','BA',7,''),
('Bala',7,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',7,5,'Aiden Markram','LSG','BA',9,''),
('Bala',7,6,'Anshul Kamboj','CSK','AL',7,''),
('Bala',7,7,'Vijaykumar Vyshak','PBKS','BO',7.5,'VC'),
('Bala',7,8,'Sanju Samson','CSK','WK',8.5,'BAI'),
('Bala',7,9,'Axar Patel','DC','AL',8.5,''),
('Bala',7,10,'Finn Allen','KKR','BA',8,''),
('Bala',7,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',8,1,'Mitchell Santner','MI','AL',9,'C'),
('Bala',8,2,'David Miller','DC','BA',9,'VC'),
('Bala',8,3,'Pathum Nissanka','DC','BA',8,'BAI'),
('Bala',8,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',8,5,'Aiden Markram','LSG','BA',9,''),
('Bala',8,6,'Mukesh Kumar','DC','BO',8,''),
('Bala',8,7,'Trent Boult','MI','BO',9,''),
('Bala',8,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',8,9,'Axar Patel','DC','AL',8.5,''),
('Bala',8,10,'Finn Allen','KKR','BA',8,''),
('Bala',8,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',9,1,'Jos Buttler','GT','WK',9.5,'VC'),
('Bala',9,2,'Rahul Tewatia','GT','AL',8,''),
('Bala',9,3,'Dhruv Jurel','RR','WK',8,'C'),
('Bala',9,4,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Bala',9,5,'Aiden Markram','LSG','BA',9,''),
('Bala',9,6,'Sai Sudharsan','GT','BA',8,'BAI'),
('Bala',9,7,'Sandeep Sharma','RR','BO',8.5,''),
('Bala',9,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',9,9,'Axar Patel','DC','AL',8.5,''),
('Bala',9,10,'Finn Allen','KKR','BA',8,''),
('Bala',9,11,'Jasprit Bumrah','MI','BO',10,''),
('Bala',10,1,'Ishan Kishan','SRH','WK',9,'C'),
('Bala',10,2,'Ayush Badoni','LSG','BA',7.5,''),
('Bala',10,3,'Shivang Kumar','SRH','BO',7,''),
('Bala',10,4,'Nicholas Pooran','LSG','WK',9.5,'VC'),
('Bala',10,5,'Aiden Markram','LSG','BA',9,''),
('Bala',10,6,'Sai Sudharsan','GT','BA',8,''),
('Bala',10,7,'Travis Head','SRH','BA',9,'BAI'),
('Bala',10,8,'Sanju Samson','CSK','WK',8.5,''),
('Bala',10,9,'Axar Patel','DC','AL',8.5,''),
('Bala',10,10,'Finn Allen','KKR','BA',8,''),
('Bala',10,11,'Jasprit Bumrah','MI','BO',10,''),
('Jeba',1,1,'Phil Salt','RCB','WK',8.5,'VC'),
('Jeba',1,2,'Virat Kohli','RCB','BA',9,'BAI'),
('Jeba',1,3,'Rajat Patidar','RCB','BA',8,''),
('Jeba',1,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',1,5,'Heinrich Klaasen','SRH','WK',8.5,''),
('Jeba',1,6,'Romario Shepherd','RCB','AL',8,''),
('Jeba',1,7,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Jeba',1,8,'Travis Head','SRH','BA',9,''),
('Jeba',1,9,'Tim David','RCB','BA',8.5,''),
('Jeba',1,10,'Suyash Sharma','RCB','BO',7,''),
('Jeba',1,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',2,1,'Phil Salt','RCB','WK',8.5,''),
('Jeba',2,2,'Virat Kohli','RCB','BA',9,''),
('Jeba',2,3,'Rajat Patidar','RCB','BA',8,''),
('Jeba',2,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',2,5,'Ryan Rickelton','MI','WK',8,'C'),
('Jeba',2,6,'Sunil Narine','KKR','AL',8.5,'VC'),
('Jeba',2,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',2,8,'Travis Head','SRH','BA',9,''),
('Jeba',2,9,'Tim David','RCB','BA',8.5,''),
('Jeba',2,10,'Kartik Tyagi','KKR','BO',7,'BOI'),
('Jeba',2,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',3,1,'Sanju Samson','CSK','WK',8.5,'C'),
('Jeba',3,2,'Virat Kohli','RCB','BA',9,''),
('Jeba',3,3,'Rajat Patidar','RCB','BA',8,''),
('Jeba',3,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',3,5,'Ruturaj Gaikwad','CSK','BA',9,'BAI'),
('Jeba',3,6,'Jamie Overton','CSK','AL',8,''),
('Jeba',3,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',3,8,'Travis Head','SRH','BA',9,''),
('Jeba',3,9,'Vaibhav Sooryavanshi','RR','BA',8,'VC'),
('Jeba',3,10,'Jofra Archer','RR','BO',8.5,''),
('Jeba',3,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',4,1,'Sanju Samson','CSK','WK',8.5,''),
('Jeba',4,2,'Virat Kohli','RCB','BA',9,''),
('Jeba',4,3,'Rajat Patidar','RCB','BA',8,''),
('Jeba',4,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',4,5,'Priyansh Arya','PBKS','BA',7.5,'C'),
('Jeba',4,6,'Xavier Bartlett','PBKS','BO',7,'BOI'),
('Jeba',4,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',4,8,'Travis Head','SRH','BA',9,''),
('Jeba',4,9,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Jeba',4,10,'Ashok Sharma','GT','BO',7,'VC'),
('Jeba',4,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',5,1,'Sanju Samson','CSK','WK',8.5,''),
('Jeba',5,2,'Tristan Stubbs','DC','BA',8,'VC'),
('Jeba',5,3,'T Natarajan','DC','BO',8,''),
('Jeba',5,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',5,5,'Priyansh Arya','PBKS','BA',7.5,''),
('Jeba',5,6,'Aiden Markram','LSG','BA',9,'C'),
('Jeba',5,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',5,8,'Travis Head','SRH','BA',9,''),
('Jeba',5,9,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Jeba',5,10,'Mohammed Shami','LSG','BO',8,'BOI'),
('Jeba',5,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',6,1,'Sanju Samson','CSK','WK',8.5,''),
('Jeba',6,2,'Sunil Narine','KKR','AL',8.5,''),
('Jeba',6,3,'Finn Allen','KKR','BA',8,'C'),
('Jeba',6,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',6,5,'Priyansh Arya','PBKS','BA',7.5,''),
('Jeba',6,6,'Heinrich Klaasen','SRH','WK',8.5,'VC'),
('Jeba',6,7,'Abhishek Sharma','SRH','AL',8.5,'BAI'),
('Jeba',6,8,'Travis Head','SRH','BA',9,''),
('Jeba',6,9,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Jeba',6,10,'Kartik Tyagi','KKR','BO',7,''),
('Jeba',6,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',7,1,'Sanju Samson','CSK','WK',8.5,'C'),
('Jeba',7,2,'Jamie Overton','CSK','AL',8,''),
('Jeba',7,3,'Finn Allen','KKR','BA',8,''),
('Jeba',7,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',7,5,'Priyansh Arya','PBKS','BA',7.5,'VC'),
('Jeba',7,6,'Ruturaj Gaikwad','CSK','BA',9,'BAI'),
('Jeba',7,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',7,8,'Travis Head','SRH','BA',9,''),
('Jeba',7,9,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Jeba',7,10,'Xavier Bartlett','PBKS','BO',7,''),
('Jeba',7,11,'Harshal Patel','SRH','BO',8.5,''),
('Jeba',8,1,'Sanju Samson','CSK','WK',8.5,''),
('Jeba',8,2,'Tristan Stubbs','DC','BA',8,'VC'),
('Jeba',8,3,'Finn Allen','KKR','BA',8,''),
('Jeba',8,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',8,5,'Priyansh Arya','PBKS','BA',7.5,''),
('Jeba',8,6,'Ryan Rickelton','MI','WK',8,'C'),
('Jeba',8,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',8,8,'Travis Head','SRH','BA',9,''),
('Jeba',8,9,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Jeba',8,10,'T Natarajan','DC','BO',8,'BOI'),
('Jeba',8,11,'Dushmantha Chameera','DC','BO',8,''),
('Jeba',9,1,'Sanju Samson','CSK','WK',8.5,''),
('Jeba',9,2,'Sai Kishore','GT','BO',8,''),
('Jeba',9,3,'Finn Allen','KKR','BA',8,''),
('Jeba',9,4,'Ishan Kishan','SRH','WK',9,''),
('Jeba',9,5,'Priyansh Arya','PBKS','BA',7.5,''),
('Jeba',9,6,'Ashok Sharma','GT','BO',7,''),
('Jeba',9,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',9,8,'Travis Head','SRH','BA',9,''),
('Jeba',9,9,'Vaibhav Sooryavanshi','RR','BA',8,'C'),
('Jeba',9,10,'Jofra Archer','RR','BO',8.5,'VC'),
('Jeba',9,11,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Jeba',10,1,'Sanju Samson','CSK','WK',8.5,''),
('Jeba',10,2,'Heinrich Klaasen','SRH','WK',8.5,'VC'),
('Jeba',10,3,'Finn Allen','KKR','BA',8,''),
('Jeba',10,4,'Ishan Kishan','SRH','WK',9,'BAI'),
('Jeba',10,5,'Priyansh Arya','PBKS','BA',7.5,''),
('Jeba',10,6,'Aiden Markram','LSG','BA',9,'C'),
('Jeba',10,7,'Abhishek Sharma','SRH','AL',8.5,''),
('Jeba',10,8,'Travis Head','SRH','BA',9,''),
('Jeba',10,9,'Liam Livingstone','SRH','AL',8.5,''),
('Jeba',10,10,'Mohammed Shami','LSG','BO',8,''),
('Jeba',10,11,'Naman Tiwari','LSG','BO',7,''),
('Johny',1,1,'Phil Salt','RCB','WK',8.5,''),
('Johny',1,2,'Suryakumar Yadav','MI','BA',10,''),
('Johny',1,3,'Krunal Pandya','RCB','AL',8.5,'C'),
('Johny',1,4,'Sunil Narine','KKR','AL',8.5,''),
('Johny',1,5,'Travis Head','SRH','BA',9,''),
('Johny',1,6,'Virat Kohli','RCB','BA',9,'BAI'),
('Johny',1,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',1,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',1,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',1,10,'Ishan Kishan','SRH','WK',9,'VC'),
('Johny',1,11,'Jaydev Unadkat','SRH','BO',8,''),
('Johny',2,1,'Phil Salt','RCB','WK',8.5,''),
('Johny',2,2,'Suryakumar Yadav','MI','BA',10,''),
('Johny',2,3,'Rohit Sharma','MI','BA',9,'BAI'),
('Johny',2,4,'Sunil Narine','KKR','AL',8.5,'C'),
('Johny',2,5,'Travis Head','SRH','BA',9,''),
('Johny',2,6,'Finn Allen','KKR','BA',8,''),
('Johny',2,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',2,8,'Varun Chakravarthy','KKR','BO',8,'VC'),
('Johny',2,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',2,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',2,11,'Jaydev Unadkat','SRH','BO',8,''),
('Johny',3,1,'Phil Salt','RCB','WK',8.5,''),
('Johny',3,2,'Yashasvi Jaiswal','RR','BA',9,'C'),
('Johny',3,3,'Ruturaj Gaikwad','CSK','BA',9,'BAI'),
('Johny',3,4,'Sanju Samson','CSK','WK',8.5,'VC'),
('Johny',3,5,'Travis Head','SRH','BA',9,''),
('Johny',3,6,'Finn Allen','KKR','BA',8,''),
('Johny',3,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',3,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',3,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',3,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',3,11,'Jaydev Unadkat','SRH','BO',8,''),
('Johny',4,1,'Jos Buttler','GT','WK',9.5,'C'),
('Johny',4,2,'Shreyas Iyer','PBKS','BA',9,'VC'),
('Johny',4,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',4,4,'Sanju Samson','CSK','WK',8.5,''),
('Johny',4,5,'Travis Head','SRH','BA',9,''),
('Johny',4,6,'Finn Allen','KKR','BA',8,''),
('Johny',4,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',4,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',4,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',4,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',4,11,'Yuzvendra Chahal','PBKS','BO',8.5,'BOI'),
('Johny',5,1,'Nicholas Pooran','LSG','WK',9.5,'VC'),
('Johny',5,2,'KL Rahul','DC','WK',9,'C'),
('Johny',5,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',5,4,'Sanju Samson','CSK','WK',8.5,''),
('Johny',5,5,'Travis Head','SRH','BA',9,''),
('Johny',5,6,'Finn Allen','KKR','BA',8,''),
('Johny',5,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',5,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',5,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',5,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',5,11,'Avesh Khan','LSG','BO',8.5,'BOI'),
('Johny',6,1,'Nicholas Pooran','LSG','WK',9.5,''),
('Johny',6,2,'KL Rahul','DC','WK',9,''),
('Johny',6,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',6,4,'Sanju Samson','CSK','WK',8.5,''),
('Johny',6,5,'Travis Head','SRH','BA',9,''),
('Johny',6,6,'Finn Allen','KKR','BA',8,''),
('Johny',6,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',6,8,'Varun Chakravarthy','KKR','BO',8,'BOI'),
('Johny',6,9,'Abhishek Sharma','SRH','AL',8.5,'VC'),
('Johny',6,10,'Ishan Kishan','SRH','WK',9,'C'),
('Johny',6,11,'Jaydev Unadkat','SRH','BO',8,''),
('Johny',7,1,'Nicholas Pooran','LSG','WK',9.5,''),
('Johny',7,2,'KL Rahul','DC','WK',9,''),
('Johny',7,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',7,4,'Sanju Samson','CSK','WK',8.5,'VC'),
('Johny',7,5,'Travis Head','SRH','BA',9,''),
('Johny',7,6,'Shreyas Iyer','PBKS','BA',9,'C'),
('Johny',7,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',7,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',7,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',7,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',7,11,'Yuzvendra Chahal','PBKS','BO',8.5,'BOI'),
('Johny',8,1,'Nicholas Pooran','LSG','WK',9.5,''),
('Johny',8,2,'KL Rahul','DC','WK',9,'BAI'),
('Johny',8,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',8,4,'Corbin Bosch','MI','AL',7.5,'VC'),
('Johny',8,5,'Travis Head','SRH','BA',9,''),
('Johny',8,6,'Ryan Rickelton','MI','WK',8,'C'),
('Johny',8,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',8,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',8,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',8,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',8,11,'Yuzvendra Chahal','PBKS','BO',8.5,''),
('Johny',9,1,'Nicholas Pooran','LSG','WK',9.5,''),
('Johny',9,2,'Jos Buttler','GT','WK',9.5,'C'),
('Johny',9,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',9,4,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Johny',9,5,'Travis Head','SRH','BA',9,''),
('Johny',9,6,'Vaibhav Sooryavanshi','RR','BA',8,'VC'),
('Johny',9,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',9,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',9,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Johny',9,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',9,11,'Yuzvendra Chahal','PBKS','BO',8.5,''),
('Johny',10,1,'Nicholas Pooran','LSG','WK',9.5,'VC'),
('Johny',10,2,'Avesh Khan','LSG','BO',8.5,''),
('Johny',10,3,'Ruturaj Gaikwad','CSK','BA',9,''),
('Johny',10,4,'Yashasvi Jaiswal','RR','BA',9,''),
('Johny',10,5,'Travis Head','SRH','BA',9,''),
('Johny',10,6,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Johny',10,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Johny',10,8,'Varun Chakravarthy','KKR','BO',8,''),
('Johny',10,9,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Johny',10,10,'Ishan Kishan','SRH','WK',9,''),
('Johny',10,11,'Jaydev Unadkat','SRH','BO',8,'BOI'),
('Mansur',1,1,'Tim David','RCB','BA',8.5,'C'),
('Mansur',1,2,'Phil Salt','RCB','WK',8.5,'BAI'),
('Mansur',1,3,'Nitish Kumar Reddy','SRH','AL',8.5,'VC'),
('Mansur',1,4,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',1,5,'Ishan Kishan','SRH','WK',9,''),
('Mansur',1,6,'Rajat Patidar','RCB','BA',8,''),
('Mansur',1,7,'Varun Chakravarthy','KKR','BO',8,''),
('Mansur',1,8,'Noor Ahmad','CSK','BO',8,''),
('Mansur',1,9,'Ajinkya Rahane','KKR','BA',8.5,''),
('Mansur',1,10,'Rohit Sharma','MI','BA',9,''),
('Mansur',1,11,'Hardik Pandya','MI','AL',11,''),
('Mansur',2,1,'Varun Chakravarthy','KKR','BO',8,''),
('Mansur',2,2,'Ajinkya Rahane','KKR','BA',8.5,''),
('Mansur',2,3,'Rohit Sharma','MI','BA',9,''),
('Mansur',2,4,'Hardik Pandya','MI','AL',11,'VC'),
('Mansur',2,5,'Cameron Green','KKR','AL',8.5,'C'),
('Mansur',2,6,'Finn Allen','KKR','BA',8,''),
('Mansur',2,7,'Jasprit Bumrah','MI','BO',10,'BOI'),
('Mansur',2,8,'Noor Ahmad','CSK','BO',8,''),
('Mansur',2,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',2,10,'Ishan Kishan','SRH','WK',9,''),
('Mansur',2,11,'Rajat Patidar','RCB','BA',8,''),
('Mansur',3,1,'Varun Chakravarthy','KKR','BO',8,''),
('Mansur',3,2,'Ajinkya Rahane','KKR','BA',8.5,''),
('Mansur',3,3,'Rohit Sharma','MI','BA',9,''),
('Mansur',3,4,'Hardik Pandya','MI','AL',11,''),
('Mansur',3,5,'Cameron Green','KKR','AL',8.5,''),
('Mansur',3,6,'Finn Allen','KKR','BA',8,''),
('Mansur',3,7,'Jasprit Bumrah','MI','BO',10,''),
('Mansur',3,8,'Noor Ahmad','CSK','BO',8,''),
('Mansur',3,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',3,10,'Ishan Kishan','SRH','WK',9,''),
('Mansur',3,11,'Rajat Patidar','RCB','BA',8,''),
('Mansur',4,1,'Mohammed Siraj','GT','BO',8.5,''),
('Mansur',4,2,'Shubman Gill','GT','BA',9,'BAI'),
('Mansur',4,3,'Marcus Stoinis','PBKS','AL',9.5,'C'),
('Mansur',4,4,'Prabhsimran Singh','PBKS','WK',8,'VC'),
('Mansur',4,5,'Shreyas Iyer','PBKS','BA',9,''),
('Mansur',4,6,'Varun Chakravarthy','KKR','BO',8,''),
('Mansur',4,7,'Ajinkya Rahane','KKR','BA',8.5,''),
('Mansur',4,8,'Finn Allen','KKR','BA',8,''),
('Mansur',4,9,'Noor Ahmad','CSK','BO',8,''),
('Mansur',4,10,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',4,11,'Ishan Kishan','SRH','WK',9,''),
('Mansur',5,1,'Rishabh Pant','LSG','WK',9,'VC'),
('Mansur',5,2,'Anrich Nortje','LSG','BO',8.5,'BOI'),
('Mansur',5,3,'KL Rahul','DC','WK',9,'C'),
('Mansur',5,4,'Prabhsimran Singh','PBKS','WK',8,''),
('Mansur',5,5,'Shreyas Iyer','PBKS','BA',9,''),
('Mansur',5,6,'Axar Patel','DC','AL',8.5,''),
('Mansur',5,7,'Ajinkya Rahane','KKR','BA',8.5,''),
('Mansur',5,8,'Finn Allen','KKR','BA',8,''),
('Mansur',5,9,'Noor Ahmad','CSK','BO',8,''),
('Mansur',5,10,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',5,11,'Ishan Kishan','SRH','WK',9,''),
('Mansur',6,1,'Ajinkya Rahane','KKR','BA',8.5,''),
('Mansur',6,2,'Finn Allen','KKR','BA',8,'C'),
('Mansur',6,3,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',6,4,'Ishan Kishan','SRH','WK',9,'VC'),
('Mansur',6,5,'Cameron Green','KKR','AL',8.5,'BAI'),
('Mansur',6,6,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Mansur',6,7,'Rahul Chahar','CSK','BO',8,''),
('Mansur',6,8,'Axar Patel','DC','AL',8.5,''),
('Mansur',6,9,'Prabhsimran Singh','PBKS','WK',8,''),
('Mansur',6,10,'Shreyas Iyer','PBKS','BA',9,''),
('Mansur',6,11,'Noor Ahmad','CSK','BO',8,''),
('Mansur',7,1,'Prabhsimran Singh','PBKS','WK',8,''),
('Mansur',7,2,'Shreyas Iyer','PBKS','BA',9,'BAI'),
('Mansur',7,3,'Noor Ahmad','CSK','BO',8,''),
('Mansur',7,4,'Marcus Stoinis','PBKS','AL',9.5,'C'),
('Mansur',7,5,'Khaleel Ahmed','CSK','BO',8,''),
('Mansur',7,6,'Sanju Samson','CSK','WK',8.5,'VC'),
('Mansur',7,7,'Axar Patel','DC','AL',8.5,''),
('Mansur',7,8,'Ayush Mhatre','CSK','BA',7,''),
('Mansur',7,9,'Finn Allen','KKR','BA',8,''),
('Mansur',7,10,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',7,11,'Ishan Kishan','SRH','WK',9,''),
('Mansur',8,1,'Axar Patel','DC','AL',8.5,''),
('Mansur',8,2,'Jasprit Bumrah','MI','BO',10,'BOI'),
('Mansur',8,3,'Rohit Sharma','MI','BA',9,'C'),
('Mansur',8,4,'KL Rahul','DC','WK',9,'VC'),
('Mansur',8,5,'Sanju Samson','CSK','WK',8.5,''),
('Mansur',8,6,'Ryan Rickelton','MI','WK',8,''),
('Mansur',8,7,'Khaleel Ahmed','CSK','BO',8,''),
('Mansur',8,8,'Ayush Mhatre','CSK','BA',7,''),
('Mansur',8,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',8,10,'Ishan Kishan','SRH','WK',9,''),
('Mansur',8,11,'Finn Allen','KKR','BA',8,''),
('Mansur',9,1,'Kumar Kushagra','GT','WK',7,'BAI'),
('Mansur',9,2,'Mohammed Siraj','GT','BO',8.5,''),
('Mansur',9,3,'Ravi Bishnoi','RR','BO',8.5,''),
('Mansur',9,4,'Shimron Hetmyer','RR','BA',8.5,'VC'),
('Mansur',9,5,'Vaibhav Sooryavanshi','RR','BA',8,'C'),
('Mansur',9,6,'Sanju Samson','CSK','WK',8.5,''),
('Mansur',9,7,'Khaleel Ahmed','CSK','BO',8,''),
('Mansur',9,8,'Ayush Mhatre','CSK','BA',7,''),
('Mansur',9,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Mansur',9,10,'Ishan Kishan','SRH','WK',9,''),
('Mansur',9,11,'Finn Allen','KKR','BA',8,''),
('Mansur',10,1,'Abhishek Sharma','SRH','AL',8.5,'BAI'),
('Mansur',10,2,'Ishan Kishan','SRH','WK',9,''),
('Mansur',10,3,'Nitish Kumar Reddy','SRH','AL',8.5,'VC'),
('Mansur',10,4,'Rishabh Pant','LSG','WK',9,'C'),
('Mansur',10,5,'Digvesh Rathi','LSG','BO',7.5,''),
('Mansur',10,6,'Kumar Kushagra','GT','WK',7,''),
('Mansur',10,7,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Mansur',10,8,'Sanju Samson','CSK','WK',8.5,''),
('Mansur',10,9,'Khaleel Ahmed','CSK','BO',8,''),
('Mansur',10,10,'Ayush Mhatre','CSK','BA',7,''),
('Mansur',10,11,'Finn Allen','KKR','BA',8,''),
('Murali',1,1,'Bhuvneshwar Kumar','RCB','BO',9,''),
('Murali',1,2,'Jitesh Sharma','RCB','WK',8.5,''),
('Murali',1,3,'Harshal Patel','SRH','BO',8.5,''),
('Murali',1,4,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Murali',1,5,'Virat Kohli','RCB','BA',9,'BAI'),
('Murali',1,6,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Murali',1,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Murali',1,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',1,9,'Ishan Kishan','SRH','WK',9,'VC'),
('Murali',1,10,'Travis Head','SRH','BA',9,''),
('Murali',1,11,'Ruturaj Gaikwad','CSK','BA',9,''),
('Murali',2,1,'Rinku Singh','KKR','BA',8.5,'VC'),
('Murali',2,2,'Suryakumar Yadav','MI','BA',10,'BAI'),
('Murali',2,3,'Harshal Patel','SRH','BO',8.5,''),
('Murali',2,4,'Finn Allen','KKR','BA',8,'C'),
('Murali',2,5,'Blessing Muzarabani','KKR','BO',7,''),
('Murali',2,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',2,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Murali',2,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',2,9,'Ishan Kishan','SRH','WK',9,''),
('Murali',2,10,'Travis Head','SRH','BA',9,''),
('Murali',2,11,'Ruturaj Gaikwad','CSK','BA',9,''),
('Murali',3,1,'Ravindra Jadeja','RR','AL',9,'VC'),
('Murali',3,2,'Sanju Samson','CSK','WK',8.5,'C'),
('Murali',3,3,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Murali',3,4,'Finn Allen','KKR','BA',8,''),
('Murali',3,5,'Blessing Muzarabani','KKR','BO',7,''),
('Murali',3,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',3,7,'Matthew Short','CSK','BA',8,''),
('Murali',3,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',3,9,'Ishan Kishan','SRH','WK',9,''),
('Murali',3,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',3,11,'Ruturaj Gaikwad','CSK','BA',9,''),
('Murali',4,1,'Marco Jansen','PBKS','AL',8.5,'VC'),
('Murali',4,2,'Glenn Phillips','GT','AL',8,'C'),
('Murali',4,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Murali',4,4,'Finn Allen','KKR','BA',8,''),
('Murali',4,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',4,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',4,7,'Prasidh Krishna','GT','BO',8,'BOI'),
('Murali',4,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',4,9,'Ishan Kishan','SRH','WK',9,''),
('Murali',4,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',4,11,'Shreyas Iyer','PBKS','BA',9,''),
('Murali',5,1,'Kuldeep Yadav','DC','BO',8.5,'VC'),
('Murali',5,2,'Pathum Nissanka','DC','BA',8,'BAI'),
('Murali',5,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Murali',5,4,'Finn Allen','KKR','BA',8,''),
('Murali',5,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',5,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',5,7,'Nicholas Pooran','LSG','WK',9.5,'C'),
('Murali',5,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',5,9,'Ishan Kishan','SRH','WK',9,''),
('Murali',5,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',5,11,'Shreyas Iyer','PBKS','BA',9,''),
('Murali',6,1,'Harshal Patel','SRH','BO',8.5,''),
('Murali',6,2,'Pathum Nissanka','DC','BA',8,''),
('Murali',6,3,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Murali',6,4,'Finn Allen','KKR','BA',8,'C'),
('Murali',6,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',6,6,'Abhishek Sharma','SRH','AL',8.5,'BAI'),
('Murali',6,7,'Rinku Singh','KKR','BA',8.5,'VC'),
('Murali',6,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',6,9,'Ishan Kishan','SRH','WK',9,''),
('Murali',6,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',6,11,'Shreyas Iyer','PBKS','BA',9,''),
('Murali',7,1,'Marco Jansen','PBKS','AL',8.5,'VC'),
('Murali',7,2,'Pathum Nissanka','DC','BA',8,''),
('Murali',7,3,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Murali',7,4,'Finn Allen','KKR','BA',8,''),
('Murali',7,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',7,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',7,7,'Sanju Samson','CSK','WK',8.5,'C'),
('Murali',7,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',7,9,'Kuldeep Yadav','DC','BO',8.5,''),
('Murali',7,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',7,11,'Shreyas Iyer','PBKS','BA',9,'BAI'),
('Murali',8,1,'Kuldeep Yadav','DC','BO',8.5,'VC'),
('Murali',8,2,'Pathum Nissanka','DC','BA',8,'BAI'),
('Murali',8,3,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Murali',8,4,'KL Rahul','DC','WK',9,''),
('Murali',8,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',8,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',8,7,'Suryakumar Yadav','MI','BA',10,'C'),
('Murali',8,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',8,9,'Sameer Rizvi','DC','BA',7,''),
('Murali',8,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',8,11,'Shreyas Iyer','PBKS','BA',9,''),
('Murali',9,1,'Prasidh Krishna','GT','BO',8,'BOI'),
('Murali',9,2,'Pathum Nissanka','DC','BA',8,''),
('Murali',9,3,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Murali',9,4,'KL Rahul','DC','WK',9,''),
('Murali',9,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',9,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Murali',9,7,'Glenn Phillips','GT','AL',8,'C'),
('Murali',9,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',9,9,'Ravindra Jadeja','RR','AL',9,'VC'),
('Murali',9,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',9,11,'Shreyas Iyer','PBKS','BA',9,''),
('Murali',10,1,'Harshal Patel','SRH','BO',8.5,''),
('Murali',10,2,'Pathum Nissanka','DC','BA',8,''),
('Murali',10,3,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Murali',10,4,'Ishan Kishan','SRH','WK',9,'BAI'),
('Murali',10,5,'Sai Sudharsan','GT','BA',8,''),
('Murali',10,6,'Abhishek Sharma','SRH','AL',8.5,'VC'),
('Murali',10,7,'Nicholas Pooran','LSG','WK',9.5,'C'),
('Murali',10,8,'Jasprit Bumrah','MI','BO',10,''),
('Murali',10,9,'Mayank Yadav','LSG','BO',7,''),
('Murali',10,10,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Murali',10,11,'Shreyas Iyer','PBKS','BA',9,''),
('Pandiyan',1,1,'Abhinandan Singh','RCB','BO',7,''),
('Pandiyan',1,2,'Hardik Pandya','MI','AL',11,''),
('Pandiyan',1,3,'Suryakumar Yadav','MI','BA',10,''),
('Pandiyan',1,4,'Virat Kohli','RCB','BA',9,'BAI'),
('Pandiyan',1,5,'Rajat Patidar','RCB','BA',8,''),
('Pandiyan',1,6,'Bhuvneshwar Kumar','RCB','BO',9,''),
('Pandiyan',1,7,'Romario Shepherd','RCB','AL',8,''),
('Pandiyan',1,8,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Pandiyan',1,9,'Nitish Kumar Reddy','SRH','AL',8.5,'VC'),
('Pandiyan',1,10,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',1,11,'Travis Head','SRH','BA',9,''),
('Pandiyan',2,1,'Varun Chakravarthy','KKR','BO',8,''),
('Pandiyan',2,2,'Angkrish Raghuvanshi','KKR','BA',7.5,'VC'),
('Pandiyan',2,3,'Hardik Pandya','MI','AL',11,'C'),
('Pandiyan',2,4,'Suryakumar Yadav','MI','BA',10,''),
('Pandiyan',2,5,'Shardul Thakur','MI','BO',8,''),
('Pandiyan',2,6,'Rohit Sharma','MI','BA',9,'BAI'),
('Pandiyan',2,7,'Rajat Patidar','RCB','BA',8,''),
('Pandiyan',2,8,'Bhuvneshwar Kumar','RCB','BO',9,''),
('Pandiyan',2,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',2,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',2,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',3,1,'Kartik Sharma','CSK','WK',7,''),
('Pandiyan',3,2,'Khaleel Ahmed','CSK','BO',8,''),
('Pandiyan',3,3,'Sanju Samson','CSK','WK',8.5,'C'),
('Pandiyan',3,4,'Matthew Short','CSK','BA',8,'VC'),
('Pandiyan',3,5,'Prashant Veer','CSK','AL',7,''),
('Pandiyan',3,6,'Rajat Patidar','RCB','BA',8,''),
('Pandiyan',3,7,'Bhuvneshwar Kumar','RCB','BO',9,''),
('Pandiyan',3,8,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Pandiyan',3,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',3,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',3,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',4,1,'Nehal Wadhera','PBKS','BA',7.5,''),
('Pandiyan',4,2,'Harpreet Brar','PBKS','BO',8,''),
('Pandiyan',4,3,'Sanju Samson','CSK','WK',8.5,''),
('Pandiyan',4,4,'Shubman Gill','GT','BA',9,'C'),
('Pandiyan',4,5,'M Shahrukh Khan','GT','BA',8,''),
('Pandiyan',4,6,'Washington Sundar','GT','AL',8,'VC'),
('Pandiyan',4,7,'Shreyas Iyer','PBKS','BA',9,'BAI'),
('Pandiyan',4,8,'Bhuvneshwar Kumar','RCB','BO',9,''),
('Pandiyan',4,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',4,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',4,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',5,1,'Sanju Samson','CSK','WK',8.5,''),
('Pandiyan',5,2,'Lungi Ngidi','DC','BO',8,''),
('Pandiyan',5,3,'Vipraj Nigam','DC','BO',7.5,''),
('Pandiyan',5,4,'KL Rahul','DC','WK',9,'C'),
('Pandiyan',5,5,'Nitish Rana','DC','BA',8,'VC'),
('Pandiyan',5,6,'Mitchell Marsh','LSG','AL',9,'BAI'),
('Pandiyan',5,7,'Mohsin Khan','LSG','BO',7.5,''),
('Pandiyan',5,8,'Mukul Choudhary','LSG','BA',7,''),
('Pandiyan',5,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',5,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',5,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',6,1,'Sanju Samson','CSK','WK',8.5,''),
('Pandiyan',6,2,'Kartik Sharma','CSK','WK',7,''),
('Pandiyan',6,3,'Khaleel Ahmed','CSK','BO',8,''),
('Pandiyan',6,4,'KL Rahul','DC','WK',9,''),
('Pandiyan',6,5,'Varun Chakravarthy','KKR','BO',8,''),
('Pandiyan',6,6,'Angkrish Raghuvanshi','KKR','BA',7.5,'VC'),
('Pandiyan',6,7,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Pandiyan',6,8,'Heinrich Klaasen','SRH','WK',8.5,''),
('Pandiyan',6,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',6,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',6,11,'Ishan Kishan','SRH','WK',9,'BAI'),
('Pandiyan',7,1,'Sanju Samson','CSK','WK',8.5,'C'),
('Pandiyan',7,2,'Kartik Sharma','CSK','WK',7,''),
('Pandiyan',7,3,'Khaleel Ahmed','CSK','BO',8,'BOI'),
('Pandiyan',7,4,'KL Rahul','DC','WK',9,''),
('Pandiyan',7,5,'Prashant Veer','CSK','AL',7,''),
('Pandiyan',7,6,'Harpreet Brar','PBKS','BO',8,''),
('Pandiyan',7,7,'Nehal Wadhera','PBKS','BA',7.5,'VC'),
('Pandiyan',7,8,'Heinrich Klaasen','SRH','WK',8.5,''),
('Pandiyan',7,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',7,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',7,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',8,1,'Sanju Samson','CSK','WK',8.5,''),
('Pandiyan',8,2,'Nitish Rana','DC','BA',8,''),
('Pandiyan',8,3,'Vipraj Nigam','DC','BO',7.5,''),
('Pandiyan',8,4,'KL Rahul','DC','WK',9,'C'),
('Pandiyan',8,5,'Lungi Ngidi','DC','BO',8,'BOI'),
('Pandiyan',8,6,'Shardul Thakur','MI','BO',8,''),
('Pandiyan',8,7,'Suryakumar Yadav','MI','BA',10,'VC'),
('Pandiyan',8,8,'Heinrich Klaasen','SRH','WK',8.5,''),
('Pandiyan',8,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',8,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',8,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',9,1,'Sanju Samson','CSK','WK',8.5,''),
('Pandiyan',9,2,'Washington Sundar','GT','AL',8,'VC'),
('Pandiyan',9,3,'M Shahrukh Khan','GT','BA',8,''),
('Pandiyan',9,4,'Vaibhav Sooryavanshi','RR','BA',8,'C'),
('Pandiyan',9,5,'Mohsin Khan','LSG','BO',7.5,''),
('Pandiyan',9,6,'Kumar Kushagra','GT','WK',7,'BAI'),
('Pandiyan',9,7,'Shardul Thakur','MI','BO',8,''),
('Pandiyan',9,8,'Heinrich Klaasen','SRH','WK',8.5,''),
('Pandiyan',9,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',9,10,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Pandiyan',9,11,'Ishan Kishan','SRH','WK',9,''),
('Pandiyan',10,1,'Nicholas Pooran','LSG','WK',9.5,''),
('Pandiyan',10,2,'Digvesh Rathi','LSG','BO',7.5,''),
('Pandiyan',10,3,'Mukul Choudhary','LSG','BA',7,''),
('Pandiyan',10,4,'Aiden Markram','LSG','BA',9,''),
('Pandiyan',10,5,'Mohsin Khan','LSG','BO',7.5,''),
('Pandiyan',10,6,'Mitchell Marsh','LSG','AL',9,'BAI'),
('Pandiyan',10,7,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Pandiyan',10,8,'Heinrich Klaasen','SRH','WK',8.5,''),
('Pandiyan',10,9,'Travis Head','SRH','BA',9,''),
('Pandiyan',10,10,'Nitish Kumar Reddy','SRH','AL',8.5,'VC'),
('Pandiyan',10,11,'Ishan Kishan','SRH','WK',9,''),
('Saravana',1,1,'Devdutt Padikkal','RCB','BA',8,'BAI'),
('Saravana',1,2,'Mangesh Yadav','RCB','AL',7,''),
('Saravana',1,3,'Aniket Verma','SRH','BA',7.5,''),
('Saravana',1,4,'Zeeshan Ansari','SRH','BO',7.5,''),
('Saravana',1,5,'Virat Kohli','RCB','BA',9,'C'),
('Saravana',1,6,'Ishan Kishan','SRH','WK',9,'VC'),
('Saravana',1,7,'Travis Head','SRH','BA',9,''),
('Saravana',1,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',1,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',1,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',1,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',2,1,'Deepak Chahar','MI','BO',8.5,'VC'),
('Saravana',2,2,'Hardik Pandya','MI','AL',11,'C'),
('Saravana',2,3,'Ajinkya Rahane','KKR','BA',8.5,'BAI'),
('Saravana',2,4,'Zeeshan Ansari','SRH','BO',7.5,''),
('Saravana',2,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',2,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',2,7,'Travis Head','SRH','BA',9,''),
('Saravana',2,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',2,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',2,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',2,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',3,1,'Noor Ahmad','CSK','BO',8,''),
('Saravana',3,2,'Hardik Pandya','MI','AL',11,''),
('Saravana',3,3,'Tushar Deshpande','RR','BO',8,''),
('Saravana',3,4,'Vignesh Puthur','RR','BO',7,''),
('Saravana',3,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',3,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',3,7,'Travis Head','SRH','BA',9,''),
('Saravana',3,8,'Ruturaj Gaikwad','CSK','BA',9,'C'),
('Saravana',3,9,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Saravana',3,10,'Sanju Samson','CSK','WK',8.5,'VC'),
('Saravana',3,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',4,1,'Jason Holder','GT','AL',8.5,'VC'),
('Saravana',4,2,'Sai Sudharsan','GT','BA',8,'C'),
('Saravana',4,3,'Prabhsimran Singh','PBKS','WK',8,'BAI'),
('Saravana',4,4,'Vignesh Puthur','RR','BO',7,''),
('Saravana',4,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',4,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',4,7,'Travis Head','SRH','BA',9,''),
('Saravana',4,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',4,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',4,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',4,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',5,1,'Axar Patel','DC','AL',8.5,'C'),
('Saravana',5,2,'KL Rahul','DC','WK',9,'BAI'),
('Saravana',5,3,'Digvesh Rathi','LSG','BO',7.5,'VC'),
('Saravana',5,4,'Mitchell Starc','DC','BO',8.5,''),
('Saravana',5,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',5,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',5,7,'Travis Head','SRH','BA',9,''),
('Saravana',5,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',5,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',5,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',5,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',6,1,'Aniket Verma','SRH','BA',7.5,'VC'),
('Saravana',6,2,'Axar Patel','DC','AL',8.5,''),
('Saravana',6,3,'Ajinkya Rahane','KKR','BA',8.5,'C'),
('Saravana',6,4,'Zeeshan Ansari','SRH','BO',7.5,''),
('Saravana',6,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',6,6,'Ishan Kishan','SRH','WK',9,'BAI'),
('Saravana',6,7,'Travis Head','SRH','BA',9,''),
('Saravana',6,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',6,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',6,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',6,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',7,1,'Aniket Verma','SRH','BA',7.5,''),
('Saravana',7,2,'Axar Patel','DC','AL',8.5,''),
('Saravana',7,3,'Ajinkya Rahane','KKR','BA',8.5,''),
('Saravana',7,4,'Zeeshan Ansari','SRH','BO',7.5,''),
('Saravana',7,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',7,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',7,7,'Travis Head','SRH','BA',9,''),
('Saravana',7,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',7,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',7,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',7,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',8,1,'Deepak Chahar','MI','BO',8.5,'BOI'),
('Saravana',8,2,'Axar Patel','DC','AL',8.5,'VC'),
('Saravana',8,3,'Hardik Pandya','MI','AL',11,'C'),
('Saravana',8,4,'Mitchell Starc','DC','BO',8.5,''),
('Saravana',8,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',8,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',8,7,'Travis Head','SRH','BA',9,''),
('Saravana',8,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',8,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',8,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',8,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',9,1,'Deepak Chahar','MI','BO',8.5,''),
('Saravana',9,2,'Vaibhav Sooryavanshi','RR','BA',8,'BAI'),
('Saravana',9,3,'Jason Holder','GT','AL',8.5,''),
('Saravana',9,4,'Sai Sudharsan','GT','BA',8,'C'),
('Saravana',9,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',9,6,'Ishan Kishan','SRH','WK',9,''),
('Saravana',9,7,'Travis Head','SRH','BA',9,''),
('Saravana',9,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',9,9,'Yashasvi Jaiswal','RR','BA',9,'VC'),
('Saravana',9,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',9,11,'Varun Chakravarthy','KKR','BO',8,''),
('Saravana',10,1,'Zeeshan Ansari','SRH','BO',7.5,''),
('Saravana',10,2,'Vaibhav Sooryavanshi','RR','BA',8,''),
('Saravana',10,3,'Jason Holder','GT','AL',8.5,''),
('Saravana',10,4,'Aniket Verma','SRH','BA',7.5,'VC'),
('Saravana',10,5,'Virat Kohli','RCB','BA',9,''),
('Saravana',10,6,'Ishan Kishan','SRH','WK',9,'C'),
('Saravana',10,7,'Travis Head','SRH','BA',9,'BAI'),
('Saravana',10,8,'Ruturaj Gaikwad','CSK','BA',9,''),
('Saravana',10,9,'Yashasvi Jaiswal','RR','BA',9,''),
('Saravana',10,10,'Sanju Samson','CSK','WK',8.5,''),
('Saravana',10,11,'Varun Chakravarthy','KKR','BO',8,''),
('Sashi',1,1,'Romario Shepherd','RCB','AL',8,''),
('Sashi',1,2,'Nitish Kumar Reddy','SRH','AL',8.5,''),
('Sashi',1,3,'Virat Kohli','RCB','BA',9,'C'),
('Sashi',1,4,'Eshan Malinga','SRH','BO',7,''),
('Sashi',1,5,'Venkatesh Iyer','RCB','AL',8.5,''),
('Sashi',1,6,'Abhishek Sharma','SRH','AL',8.5,'VC'),
('Sashi',1,7,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',1,8,'Phil Salt','RCB','WK',8.5,''),
('Sashi',1,9,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',1,10,'Travis Head','SRH','BA',9,'BAI'),
('Sashi',1,11,'Rasikh Salam','RCB','BO',7,''),
('Sashi',2,1,'Ramandeep Singh','KKR','BA',7.5,''),
('Sashi',2,2,'Matheesha Pathirana','KKR','BO',8,''),
('Sashi',2,3,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',2,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',2,5,'Tilak Varma','MI','AL',8.5,'C'),
('Sashi',2,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Sashi',2,7,'Naman Dhir','MI','BA',7,'VC'),
('Sashi',2,8,'Phil Salt','RCB','WK',8.5,''),
('Sashi',2,9,'Suryakumar Yadav','MI','BA',10,'BAI'),
('Sashi',2,10,'Travis Head','SRH','BA',9,''),
('Sashi',2,11,'AM Ghazanfar','MI','BO',7,''),
('Sashi',3,1,'AM Ghazanfar','MI','BO',7,''),
('Sashi',3,2,'Matheesha Pathirana','KKR','BO',8,''),
('Sashi',3,3,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',3,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',3,5,'Dhruv Jurel','RR','WK',8,'C'),
('Sashi',3,6,'Abhishek Sharma','SRH','AL',8.5,''),
('Sashi',3,7,'Sanju Samson','CSK','WK',8.5,'VC'),
('Sashi',3,8,'Phil Salt','RCB','WK',8.5,''),
('Sashi',3,9,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Sashi',3,10,'Travis Head','SRH','BA',9,''),
('Sashi',3,11,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',4,1,'Sanju Samson','CSK','WK',8.5,''),
('Sashi',4,2,'Yash Thakur','PBKS','BO',7.5,''),
('Sashi',4,3,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',4,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',4,5,'Rashid Khan','GT','AL',9.5,'C'),
('Sashi',4,6,'Yashasvi Jaiswal','RR','BA',9,''),
('Sashi',4,7,'Kagiso Rabada','GT','BO',8.5,'VC'),
('Sashi',4,8,'Phil Salt','RCB','WK',8.5,''),
('Sashi',4,9,'Priyansh Arya','PBKS','BA',7.5,'BAI'),
('Sashi',4,10,'Shashank Singh','PBKS','AL',8,''),
('Sashi',4,11,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',5,1,'Sanju Samson','CSK','WK',8.5,''),
('Sashi',5,2,'Prince Yadav','LSG','BO',7,''),
('Sashi',5,3,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',5,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',5,5,'Axar Patel','DC','AL',8.5,'C'),
('Sashi',5,6,'Yashasvi Jaiswal','RR','BA',9,''),
('Sashi',5,7,'Abdul Samad','LSG','BA',7.5,'VC'),
('Sashi',5,8,'Eshan Malinga','SRH','BO',7,''),
('Sashi',5,9,'Abishek Porel','DC','WK',7,'BAI'),
('Sashi',5,10,'Ashutosh Sharma','DC','AL',7.5,''),
('Sashi',5,11,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',6,1,'Sanju Samson','CSK','WK',8.5,''),
('Sashi',6,2,'Salil Arora','SRH','WK',7,''),
('Sashi',6,3,'Eshan Malinga','SRH','BO',7,''),
('Sashi',6,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',6,5,'Heinrich Klaasen','SRH','WK',8.5,'C'),
('Sashi',6,6,'Yashasvi Jaiswal','RR','BA',9,''),
('Sashi',6,7,'Ramandeep Singh','KKR','BA',7.5,'VC'),
('Sashi',6,8,'Axar Patel','DC','AL',8.5,''),
('Sashi',6,9,'Travis Head','SRH','BA',9,'BAI'),
('Sashi',6,10,'Matheesha Pathirana','KKR','BO',8,''),
('Sashi',6,11,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',7,1,'Shashank Singh','PBKS','AL',8,''),
('Sashi',7,2,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',7,3,'Travis Head','SRH','BA',9,''),
('Sashi',7,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',7,5,'Ruturaj Gaikwad','CSK','BA',9,'C'),
('Sashi',7,6,'Yashasvi Jaiswal','RR','BA',9,''),
('Sashi',7,7,'Priyansh Arya','PBKS','BA',7.5,'VC'),
('Sashi',7,8,'Yash Thakur','PBKS','BO',7.5,''),
('Sashi',7,9,'Sanju Samson','CSK','WK',8.5,'BAI'),
('Sashi',7,10,'Matheesha Pathirana','KKR','BO',8,''),
('Sashi',7,11,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',8,1,'Ruturaj Gaikwad','CSK','BA',9,''),
('Sashi',8,2,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',8,3,'Matheesha Pathirana','KKR','BO',8,''),
('Sashi',8,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',8,5,'Axar Patel','DC','AL',8.5,'C'),
('Sashi',8,6,'Yashasvi Jaiswal','RR','BA',9,''),
('Sashi',8,7,'Tilak Varma','MI','AL',8.5,'VC'),
('Sashi',8,8,'Travis Head','SRH','BA',9,''),
('Sashi',8,9,'Suryakumar Yadav','MI','BA',10,'BAI'),
('Sashi',8,10,'Naman Dhir','MI','BA',7,''),
('Sashi',8,11,'AM Ghazanfar','MI','BO',7,''),
('Sashi',9,1,'Ruturaj Gaikwad','CSK','BA',9,''),
('Sashi',9,2,'Heinrich Klaasen','SRH','WK',8.5,''),
('Sashi',9,3,'Matheesha Pathirana','KKR','BO',8,''),
('Sashi',9,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',9,5,'Rashid Khan','GT','AL',9.5,'C'),
('Sashi',9,6,'Kagiso Rabada','GT','BO',8.5,''),
('Sashi',9,7,'Dhruv Jurel','RR','WK',8,'VC'),
('Sashi',9,8,'Ishant Sharma','GT','BO',8,''),
('Sashi',9,9,'Yashasvi Jaiswal','RR','BA',9,'BAI'),
('Sashi',9,10,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',9,11,'Travis Head','SRH','BA',9,''),
('Sashi',10,1,'Ruturaj Gaikwad','CSK','BA',9,''),
('Sashi',10,2,'Rashid Khan','GT','AL',9.5,''),
('Sashi',10,3,'Salil Arora','SRH','WK',7,''),
('Sashi',10,4,'Virat Kohli','RCB','BA',9,''),
('Sashi',10,5,'Heinrich Klaasen','SRH','WK',8.5,'C'),
('Sashi',10,6,'Prince Yadav','LSG','BO',7,''),
('Sashi',10,7,'Abdul Samad','LSG','BA',7.5,'VC'),
('Sashi',10,8,'Eshan Malinga','SRH','BO',7,''),
('Sashi',10,9,'Travis Head','SRH','BA',9,'BAI'),
('Sashi',10,10,'Suryakumar Yadav','MI','BA',10,''),
('Sashi',10,11,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',1,1,'Phil Salt','RCB','WK',8.5,'VC'),
('Tamil',1,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',1,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',1,4,'Travis Head','SRH','BA',9,''),
('Tamil',1,5,'Shubman Gill','GT','BA',9,''),
('Tamil',1,6,'Virat Kohli','RCB','BA',9,'C'),
('Tamil',1,7,'Suryakumar Yadav','MI','BA',10,''),
('Tamil',1,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',1,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Tamil',1,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',1,11,'Jacob Duffy','RCB','BO',8,'BOI'),
('Tamil',2,1,'Sherfane Rutherford','MI','BA',8,'VC'),
('Tamil',2,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',2,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',2,4,'Finn Allen','KKR','BA',8,''),
('Tamil',2,5,'Shubman Gill','GT','BA',9,''),
('Tamil',2,6,'Rohit Sharma','MI','BA',9,'C'),
('Tamil',2,7,'Suryakumar Yadav','MI','BA',10,''),
('Tamil',2,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',2,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Tamil',2,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',2,11,'Mayank Markande','MI','BO',7.5,'BOI'),
('Tamil',3,1,'Vaibhav Sooryavanshi','RR','BA',8,'BAI'),
('Tamil',3,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',3,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',3,4,'Finn Allen','KKR','BA',8,''),
('Tamil',3,5,'Shubman Gill','GT','BA',9,''),
('Tamil',3,6,'Riyan Parag','RR','BA',8.5,'C'),
('Tamil',3,7,'Sarfaraz Khan','CSK','BA',7,''),
('Tamil',3,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',3,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Tamil',3,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',3,11,'Matt Henry','CSK','BO',8,'VC'),
('Tamil',4,1,'Cooper Connolly','PBKS','AL',7,'BAI'),
('Tamil',4,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',4,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',4,4,'Finn Allen','KKR','BA',8,''),
('Tamil',4,5,'Shubman Gill','GT','BA',9,'C'),
('Tamil',4,6,'Riyan Parag','RR','BA',8.5,''),
('Tamil',4,7,'Priyansh Arya','PBKS','BA',7.5,''),
('Tamil',4,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',4,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Tamil',4,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',4,11,'Jayant Yadav','GT','BO',8,'VC'),
('Tamil',5,1,'KL Rahul','DC','WK',9,'C'),
('Tamil',5,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',5,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',5,4,'Finn Allen','KKR','BA',8,''),
('Tamil',5,5,'Shubman Gill','GT','BA',9,''),
('Tamil',5,6,'Aiden Markram','LSG','BA',9,'VC'),
('Tamil',5,7,'Priyansh Arya','PBKS','BA',7.5,''),
('Tamil',5,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',5,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Tamil',5,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',5,11,'Mayank Yadav','LSG','BO',7,'BOI'),
('Tamil',6,1,'David Payne','SRH','BO',7,'VC'),
('Tamil',6,2,'Ishan Kishan','SRH','WK',9,'C'),
('Tamil',6,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',6,4,'Finn Allen','KKR','BA',8,'BAI'),
('Tamil',6,5,'Shubman Gill','GT','BA',9,''),
('Tamil',6,6,'Aiden Markram','LSG','BA',9,''),
('Tamil',6,7,'Priyansh Arya','PBKS','BA',7.5,''),
('Tamil',6,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',6,9,'Abhishek Sharma','SRH','AL',8.5,''),
('Tamil',6,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',6,11,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Tamil',7,1,'Cooper Connolly','PBKS','AL',7,'BAI'),
('Tamil',7,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',7,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',7,4,'Finn Allen','KKR','BA',8,''),
('Tamil',7,5,'Sarfaraz Khan','CSK','BA',7,'VC'),
('Tamil',7,6,'Aiden Markram','LSG','BA',9,''),
('Tamil',7,7,'Priyansh Arya','PBKS','BA',7.5,''),
('Tamil',7,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',7,9,'Matt Henry','CSK','BO',8,'C'),
('Tamil',7,10,'Ruturaj Gaikwad','CSK','BA',9,''),
('Tamil',7,11,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Tamil',8,1,'KL Rahul','DC','WK',9,'C'),
('Tamil',8,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',8,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',8,4,'Finn Allen','KKR','BA',8,''),
('Tamil',8,5,'Rohit Sharma','MI','BA',9,'BAI'),
('Tamil',8,6,'Aiden Markram','LSG','BA',9,''),
('Tamil',8,7,'Mayank Markande','MI','BO',7.5,'VC'),
('Tamil',8,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',8,9,'Sherfane Rutherford','MI','BA',8,''),
('Tamil',8,10,'Cooper Connolly','PBKS','AL',7,''),
('Tamil',8,11,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Tamil',9,1,'Vaibhav Sooryavanshi','RR','BA',8,'BAI'),
('Tamil',9,2,'Ishan Kishan','SRH','WK',9,''),
('Tamil',9,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',9,4,'Finn Allen','KKR','BA',8,''),
('Tamil',9,5,'Riyan Parag','RR','BA',8.5,'C'),
('Tamil',9,6,'Aiden Markram','LSG','BA',9,''),
('Tamil',9,7,'Jayant Yadav','GT','BO',8,''),
('Tamil',9,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',9,9,'Kumar Kushagra','GT','WK',7,'VC'),
('Tamil',9,10,'Glenn Phillips','GT','AL',8,''),
('Tamil',9,11,'Angkrish Raghuvanshi','KKR','BA',7.5,''),
('Tamil',10,1,'Travis Head','SRH','BA',9,''),
('Tamil',10,2,'Ishan Kishan','SRH','WK',9,'BAI'),
('Tamil',10,3,'Yashasvi Jaiswal','RR','BA',9,''),
('Tamil',10,4,'Finn Allen','KKR','BA',8,''),
('Tamil',10,5,'Abhishek Sharma','SRH','AL',8.5,'C'),
('Tamil',10,6,'Aiden Markram','LSG','BA',9,''),
('Tamil',10,7,'David Payne','SRH','BO',7,'VC'),
('Tamil',10,8,'Jasprit Bumrah','MI','BO',10,''),
('Tamil',10,9,'Kumar Kushagra','GT','WK',7,''),
('Tamil',10,10,'Glenn Phillips','GT','AL',8,''),
('Tamil',10,11,'Angkrish Raghuvanshi','KKR','BA',7.5,'');

create temporary table vt_points(match_number int,player_name text,team_code text,batting numeric,bowling numeric,fielding numeric,total numeric) on commit drop;
insert into vt_points values
(1,'Abhinandan Singh','RCB',0,26,10,38),
(1,'Bhuvneshwar Kumar','RCB',0,33,0,35),
(1,'Devdutt Padikkal','RCB',104,0,30,136),
(1,'Jacob Duffy','RCB',0,96,0,113),
(1,'Jitesh Sharma','RCB',-4,0,10,8),
(1,'Krunal Pandya','RCB',0,-8,0,-6),
(1,'Phil Salt','RCB',10,0,30,42),
(1,'Rajat Patidar','RCB',63,0,0,65),
(1,'Romario Shepherd','RCB',0,68,0,70),
(1,'Suyash Sharma','RCB',0,30,0,32),
(1,'Tim David','RCB',27,0,0,29),
(1,'Virat Kohli','RCB',104,0,10,116),
(1,'Abhishek Sharma','SRH',9,0,0,9),
(1,'Aniket Verma','SRH',78,0,0,78),
(1,'David Payne','SRH',6,48,0,54),
(1,'Eshan Malinga','SRH',0,-8,0,-8),
(1,'Harsh Dubey','SRH',3,24,10,37),
(1,'Harshal Patel','SRH',0,-8,0,-8),
(1,'Heinrich Klaasen','SRH',41,0,20,61),
(1,'Ishan Kishan','SRH',124,0,0,124),
(1,'Jaydev Unadkat','SRH',4,30,10,44),
(1,'Nitish Kumar Reddy','SRH',1,6,0,7),
(1,'Salil Arora','SRH',11,0,0,11),
(1,'Travis Head','SRH',13,0,0,13),
(2,'Ajinkya Rahane','KKR',94,0,0,94),
(2,'Angkrish Raghuvanshi','KKR',81,0,0,81),
(2,'Anukul Roy','KKR',0,-6,20,14),
(2,'Blessing Muzarabani','KKR',0,6,0,6),
(2,'Cameron Green','KKR',35,0,0,35),
(2,'Finn Allen','KKR',63,0,0,63),
(2,'Kartik Tyagi','KKR',0,34,0,34),
(2,'Ramandeep Singh','KKR',4,0,0,4),
(2,'Rinku Singh','KKR',47,0,10,57),
(2,'Sunil Narine','KKR',0,28,0,28),
(2,'Vaibhav Arora','KKR',0,28,0,28),
(2,'Varun Chakravarthy','KKR',0,-2,0,-2),
(2,'AM Ghazanfar','MI',0,0,0,2),
(2,'Hardik Pandya','MI',29,26,10,67),
(2,'Jasprit Bumrah','MI',0,2,0,4),
(2,'Mayank Markande','MI',0,-10,0,-8),
(2,'Naman Dhir','MI',6,0,0,8),
(2,'Rohit Sharma','MI',122,0,0,124),
(2,'Ryan Rickelton','MI',127,0,0,129),
(2,'Shardul Thakur','MI',0,78,0,95),
(2,'Sherfane Rutherford','MI',0,0,10,12),
(2,'Suryakumar Yadav','MI',19,0,0,21),
(2,'Tilak Varma','MI',28,0,20,50),
(2,'Trent Boult','MI',0,8,0,10),
(3,'Anshul Kamboj','CSK',4,66,0,70),
(3,'Ayush Mhatre','CSK',-4,0,0,-4),
(3,'Jamie Overton','CSK',53,-10,0,43),
(3,'Kartik Sharma','CSK',22,0,0,22),
(3,'Khaleel Ahmed','CSK',0,22,0,22),
(3,'Matt Henry','CSK',6,-6,0,0),
(3,'Matthew Short','CSK',2,0,0,2),
(3,'Noor Ahmad','CSK',1,-2,0,-1),
(3,'Ruturaj Gaikwad','CSK',3,0,0,3),
(3,'Sanju Samson','CSK',7,0,0,7),
(3,'Sarfaraz Khan','CSK',25,0,0,25),
(3,'Shivam Dube','CSK',8,0,0,8),
(3,'Brijesh Sharma','RR',0,54,0,56),
(3,'Dhruv Jurel','RR',22,0,30,54),
(3,'Jofra Archer','RR',0,89,0,91),
(3,'Nandre Burger','RR',0,82,0,84),
(3,'Ravi Bishnoi','RR',0,35,20,57),
(3,'Ravindra Jadeja','RR',0,76,0,78),
(3,'Riyan Parag','RR',21,0,0,23),
(3,'Sandeep Sharma','RR',0,24,0,26),
(3,'Shimron Hetmyer','RR',0,0,10,12),
(3,'Vaibhav Sooryavanshi','RR',104,0,0,121),
(3,'Yashasvi Jaiswal','RR',47,0,10,59),
(4,'Ashok Sharma','GT',0,32,10,42),
(4,'Glenn Phillips','GT',34,0,0,34),
(4,'Jos Buttler','GT',49,0,10,59),
(4,'Kagiso Rabada','GT',0,30,0,30),
(4,'M Shahrukh Khan','GT',4,0,0,4),
(4,'Mohammed Siraj','GT',0,10,0,10),
(4,'Prasidh Krishna','GT',0,88,10,98),
(4,'Rahul Tewatia','GT',14,0,0,14),
(4,'Rashid Khan','GT',0,40,10,50),
(4,'Sai Sudharsan','GT',17,0,0,17),
(4,'Shubman Gill','GT',51,0,20,71),
(4,'Washington Sundar','GT',22,30,10,62),
(4,'Arshdeep Singh','PBKS',0,10,20,32),
(4,'Cooper Connolly','PBKS',101,0,10,128),
(4,'Marco Jansen','PBKS',11,40,10,63),
(4,'Marcus Stoinis','PBKS',-2,0,0,0),
(4,'Nehal Wadhera','PBKS',3,0,0,5),
(4,'Prabhsimran Singh','PBKS',56,0,0,58),
(4,'Priyansh Arya','PBKS',9,0,0,11),
(4,'Shashank Singh','PBKS',4,0,0,6),
(4,'Shreyas Iyer','PBKS',30,0,10,42),
(4,'Vijaykumar Vyshak','PBKS',0,80,0,82),
(4,'Xavier Bartlett','PBKS',13,12,10,37),
(4,'Yuzvendra Chahal','PBKS',0,60,0,62),
(5,'Axar Patel','DC',-4,52,0,50),
(5,'David Miller','DC',0,0,10,12),
(5,'KL Rahul','DC',-4,0,10,8),
(5,'Kuldeep Yadav','DC',0,58,20,80),
(5,'Lungi Ngidi','DC',0,84,0,86),
(5,'Mukesh Kumar','DC',0,24,20,46),
(5,'Nitish Rana','DC',17,0,0,19),
(5,'Pathum Nissanka','DC',1,0,0,3),
(5,'Sameer Rizvi','DC',93,0,0,110),
(5,'T Natarajan','DC',0,77,0,79),
(5,'Tristan Stubbs','DC',48,0,20,70),
(5,'Vipraj Nigam','DC',0,2,0,4),
(5,'Abdul Samad','LSG',47,0,10,57),
(5,'Aiden Markram','LSG',14,-4,0,10),
(5,'Anrich Nortje','LSG',0,8,0,8),
(5,'Ayush Badoni','LSG',-2,0,0,-2),
(5,'Mitchell Marsh','LSG',49,0,0,49),
(5,'Mohammed Shami','LSG',1,44,0,45),
(5,'Mohsin Khan','LSG',0,68,10,78),
(5,'Mukul Choudhary','LSG',20,0,0,20),
(5,'Nicholas Pooran','LSG',9,0,0,9),
(5,'Prince Yadav','LSG',0,74,0,74),
(5,'Rishabh Pant','LSG',8,0,10,18),
(5,'Shahbaz Ahmed','LSG',16,-12,0,4),
(6,'Ajinkya Rahane','KKR',6,0,10,16),
(6,'Angkrish Raghuvanshi','KKR',82,0,0,82),
(6,'Anukul Roy','KKR',-2,26,0,24),
(6,'Blessing Muzarabani','KKR',0,97,0,97),
(6,'Cameron Green','KKR',2,0,10,12),
(6,'Finn Allen','KKR',82,0,0,82),
(6,'Kartik Tyagi','KKR',6,24,0,30),
(6,'Ramandeep Singh','KKR',11,0,10,21),
(6,'Rinku Singh','KKR',47,0,20,67),
(6,'Sunil Narine','KKR',16,6,0,22),
(6,'Vaibhav Arora','KKR',1,66,0,67),
(6,'Varun Chakravarthy','KKR',0,-12,20,8),
(6,'Abhishek Sharma','SRH',84,-10,0,76),
(6,'Aniket Verma','SRH',1,0,10,13),
(6,'David Payne','SRH',0,-14,0,-12),
(6,'Eshan Malinga','SRH',0,54,30,86),
(6,'Harsh Dubey','SRH',11,24,10,47),
(6,'Heinrich Klaasen','SRH',68,0,0,70),
(6,'Ishan Kishan','SRH',17,0,10,29),
(6,'Jaydev Unadkat','SRH',0,80,20,102),
(6,'Nitish Kumar Reddy','SRH',55,50,10,132),
(6,'Salil Arora','SRH',-4,0,0,-2),
(6,'Shivang Kumar','SRH',5,8,10,25),
(6,'Travis Head','SRH',74,0,0,76),
(7,'Anshul Kamboj','CSK',0,56,0,56),
(7,'Ayush Mhatre','CSK',103,0,0,103),
(7,'Kartik Sharma','CSK',1,0,0,1),
(7,'Khaleel Ahmed','CSK',0,14,0,14),
(7,'Matt Henry','CSK',0,56,10,66),
(7,'Noor Ahmad','CSK',0,6,10,16),
(7,'Prashant Veer','CSK',7,0,0,7),
(7,'Rahul Chahar','CSK',0,0,10,10),
(7,'Ruturaj Gaikwad','CSK',36,0,10,46),
(7,'Sanju Samson','CSK',8,0,0,8),
(7,'Sarfaraz Khan','CSK',64,0,10,74),
(7,'Shivam Dube','CSK',62,0,0,62),
(7,'Arshdeep Singh','PBKS',0,10,0,12),
(7,'Cooper Connolly','PBKS',52,0,0,54),
(7,'Marco Jansen','PBKS',0,48,0,50),
(7,'Marcus Stoinis','PBKS',11,-10,0,3),
(7,'Nehal Wadhera','PBKS',12,0,20,34),
(7,'Prabhsimran Singh','PBKS',57,0,10,69),
(7,'Priyansh Arya','PBKS',96,0,0,113),
(7,'Shashank Singh','PBKS',16,0,0,18),
(7,'Shreyas Iyer','PBKS',74,0,0,76),
(7,'Vijaykumar Vyshak','PBKS',0,56,0,58),
(7,'Xavier Bartlett','PBKS',0,26,0,28),
(7,'Yuzvendra Chahal','PBKS',0,28,10,40),
(8,'Axar Patel','DC',0,40,10,52),
(8,'David Miller','DC',27,0,0,29),
(8,'KL Rahul','DC',1,0,0,3),
(8,'Kuldeep Yadav','DC',0,2,0,4),
(8,'Lungi Ngidi','DC',0,44,0,46),
(8,'Mukesh Kumar','DC',0,60,20,82),
(8,'Nitish Rana','DC',-2,0,10,10),
(8,'Pathum Nissanka','DC',58,0,0,60),
(8,'Sameer Rizvi','DC',137,0,0,154),
(8,'T Natarajan','DC',0,26,0,28),
(8,'Tristan Stubbs','DC',3,0,10,15),
(8,'Vipraj Nigam','DC',0,32,0,34),
(8,'Corbin Bosch','MI',13,24,0,37),
(8,'Deepak Chahar','MI',0,42,0,42),
(8,'Jasprit Bumrah','MI',0,26,10,36),
(8,'Mayank Markande','MI',0,0,10,10),
(8,'Mitchell Santner','MI',24,36,0,60),
(8,'Naman Dhir','MI',38,0,0,38),
(8,'Rohit Sharma','MI',48,0,0,48),
(8,'Ryan Rickelton','MI',9,0,10,19),
(8,'Shardul Thakur','MI',0,-4,0,-4),
(8,'Sherfane Rutherford','MI',6,0,0,6),
(8,'Suryakumar Yadav','MI',68,0,0,68),
(8,'Tilak Varma','MI',-2,0,10,8),
(9,'Ashok Sharma','GT',0,38,0,40),
(9,'Glenn Phillips','GT',3,0,20,25),
(9,'Jos Buttler','GT',47,0,10,59),
(9,'Kagiso Rabada','GT',32,70,0,104),
(9,'Kumar Kushagra','GT',25,0,10,37),
(9,'M Shahrukh Khan','GT',14,0,0,16),
(9,'Mohammed Siraj','GT',0,34,10,46),
(9,'Prasidh Krishna','GT',0,34,0,36),
(9,'Rahul Tewatia','GT',15,0,0,17),
(9,'Rashid Khan','GT',35,26,0,63),
(9,'Sai Sudharsan','GT',102,0,0,104),
(9,'Washington Sundar','GT',5,0,0,7),
(9,'Dhruv Jurel','RR',116,0,0,116),
(9,'Donovan Ferreira','RR',1,0,0,1),
(9,'Jofra Archer','RR',1,14,20,35),
(9,'Nandre Burger','RR',0,32,0,32),
(9,'Ravi Bishnoi','RR',0,106,0,121),
(9,'Ravindra Jadeja','RR',8,-8,20,20),
(9,'Riyan Parag','RR',10,22,20,52),
(9,'Sandeep Sharma','RR',0,2,10,12),
(9,'Shimron Hetmyer','RR',23,0,10,33),
(9,'Tushar Deshpande','RR',0,32,10,42),
(9,'Vaibhav Sooryavanshi','RR',48,0,0,48),
(9,'Yashasvi Jaiswal','RR',81,0,0,81),
(10,'Abdul Samad','LSG',22,0,0,24),
(10,'Aiden Markram','LSG',65,0,10,77),
(10,'Avesh Khan','LSG',0,64,0,66),
(10,'Ayush Badoni','LSG',13,0,0,15),
(10,'Digvesh Rathi','LSG',0,26,0,28),
(10,'Manimaran Siddharth','LSG',0,40,10,52),
(10,'Mitchell Marsh','LSG',18,0,0,20),
(10,'Mohammed Shami','LSG',0,100,0,117),
(10,'Mukul Choudhary','LSG',2,0,0,4),
(10,'Nicholas Pooran','LSG',1,0,0,3),
(10,'Prince Yadav','LSG',0,77,10,89),
(10,'Rishabh Pant','LSG',87,0,30,119),
(10,'Abhishek Sharma','SRH',-2,0,0,-2),
(10,'Aniket Verma','SRH',2,0,0,2),
(10,'Eshan Malinga','SRH',0,38,0,38),
(10,'Harsh Dubey','SRH',-4,74,0,70),
(10,'Harshal Patel','SRH',5,14,0,19),
(10,'Heinrich Klaasen','SRH',85,0,0,85),
(10,'Ishan Kishan','SRH',1,0,20,21),
(10,'Jaydev Unadkat','SRH',0,2,0,2),
(10,'Liam Livingstone','SRH',12,0,20,32),
(10,'Nitish Kumar Reddy','SRH',83,-10,10,83),
(10,'Shivang Kumar','SRH',6,30,0,36),
(10,'Travis Head','SRH',8,0,0,8);

create temporary table vt_owner_scores(owner_name text,match_number int,total numeric) on commit drop;
insert into vt_owner_scores values
('Bala',1,720),
('Bala',2,395),
('Bala',3,250),
('Bala',4,347),
('Bala',5,132),
('Bala',6,630),
('Bala',7,467),
('Bala',8,456),
('Bala',9,554),
('Bala',10,326),
('Jeba',1,1365),
('Jeba',2,373),
('Jeba',3,396),
('Jeba',4,109),
('Jeba',5,322),
('Jeba',6,611),
('Jeba',7,346),
('Jeba',8,123),
('Jeba',9,351),
('Jeba',10,515),
('Johny',1,556),
('Johny',2,381),
('Johny',3,210),
('Johny',4,376),
('Johny',5,30),
('Johny',6,478),
('Johny',7,325),
('Johny',8,96),
('Johny',9,448),
('Johny',10,185),
('Mansur',1,307),
('Mansur',2,469),
('Mansur',3,-1),
('Mansur',4,283),
('Mansur',5,109),
('Mansur',6,443),
('Mansur',7,368),
('Mansur',8,239),
('Mansur',9,363),
('Mansur',10,421),
('Murali',1,538),
('Murali',2,320),
('Murali',3,441),
('Murali',4,398),
('Murali',5,145),
('Murali',6,549),
('Murali',7,344),
('Murali',8,486),
('Murali',9,305),
('Murali',10,39),
('Pandiyan',1,687),
('Pandiyan',2,637),
('Pandiyan',3,155),
('Pandiyan',4,304),
('Pandiyan',5,331),
('Pandiyan',6,717),
('Pandiyan',7,108),
('Pandiyan',8,236),
('Pandiyan',9,183),
('Pandiyan',10,841),
('Saravana',1,717),
('Saravana',2,375),
('Saravana',3,115),
('Saravana',4,166),
('Saravana',5,92),
('Saravana',6,180),
('Saravana',7,54),
('Saravana',8,162),
('Saravana',9,473),
('Saravana',10,61),
('Sashi',1,449),
('Sashi',2,161),
('Sashi',3,213),
('Sashi',4,179),
('Sashi',5,305),
('Sashi',6,404),
('Sashi',7,311),
('Sashi',8,335),
('Sashi',9,578),
('Sashi',10,349),
('Tamil',1,896),
('Tamil',2,364),
('Tamil',3,404),
('Tamil',4,355),
('Tamil',5,51),
('Tamil',6,362),
('Tamil',7,506),
('Tamil',8,184),
('Tamil',9,452),
('Tamil',10,83);

do $$
begin
 if (select count(*) from vt_lineups) <> 90 then raise exception 'Expected 90 lineups'; end if;
 if (select count(*) from vt_lineup_players) <> 990 then raise exception 'Expected 990 lineup players'; end if;
 if exists (select 1 from vt_lineup_players group by owner_name,match_number having count(*)<>11 or count(distinct player_name)<>11) then raise exception 'Every lineup must have 11 unique players'; end if;
 if (select count(*) from public.league_members where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and status='active' and role in ('league_admin','owner')) <> 9 then raise exception 'Expected 9 active owners'; end if;
 if exists (
  select 1
  from vt_lineup_players v
  left join public.cricket_teams team on team.code=v.team_code
  left join public.players p on p.full_name=v.player_name and p.team_id=team.id
  where p.id is null
 ) then raise exception 'One or more sheet players did not resolve'; end if;
 if exists (
  select 1
  from vt_sheet_roster roster
  left join public.cricket_teams team on team.code=roster.team_code
  left join public.players player
    on player.full_name=roster.player_name
   and player.team_id=team.id
  where player.id is null
 ) then raise exception 'One or more roster players did not resolve by name and team'; end if;
 if exists (
  select 1
  from vt_points points
  left join public.cricket_teams team on team.code=points.team_code
  left join public.players player
    on player.full_name=points.player_name
   and player.team_id=team.id
  where player.id is null
 ) then raise exception 'One or more point rows did not resolve by name and team'; end if;
end $$;

create table if not exists public.volume_test_match_backup (
 backup_id uuid primary key default gen_random_uuid(),
 league_id uuid not null references public.leagues(id) on delete cascade,
 created_at timestamptz not null default now(),
 label text not null,
 payload jsonb not null
);
revoke all on public.volume_test_match_backup from anon, authenticated;

insert into public.volume_test_match_backup(league_id,label,payload)
select '2fa606e1-2299-4c6d-9acf-348b7b858a49','pre-volume-test-royalty-2026-08-12',
 jsonb_build_object(
  'fixtures',(select coalesce(jsonb_agg(to_jsonb(f) order by f.match_number),'[]'::jsonb) from public.fixtures f where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'league_players',(select coalesce(jsonb_agg(to_jsonb(lp)),'[]'::jsonb) from public.league_players lp where lp.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'lineup_submissions',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.lineup_submissions x where x.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'lineup_players',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.lineup_players x join public.lineup_submissions s on s.id=x.lineup_id where s.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'lineup_boosters',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.lineup_boosters x where x.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'player_match_points',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.player_match_points x join public.fixtures f on f.id=x.fixture_id where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'member_match_scores',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.member_match_scores x join public.fixtures f on f.id=x.fixture_id where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
  'special_adjustments',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.special_player_score_adjustments x where x.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'),
 'transfer_events',(select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) from public.transfer_events x where x.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49')
 );

-- Align the volume-test pool and auction ownership with the supplied workbook.
-- Deactivate the existing pool first so a prior name-only import cannot leave a
-- same-name player from another IPL team active beside the authoritative row.
update public.league_players
set active=false,
    released_at=coalesce(released_at,now()),
    updated_at=now()
where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';

insert into public.league_players(
 league_id,player_id,owner_member_id,acquisition_type,acquisition_price,
 bid_price,active,acquired_at,released_at
)
select '2fa606e1-2299-4c6d-9acf-348b7b858a49',p.id,m.id,
       case when roster.owner_name is null then 'open' else 'auction' end,
       roster.selection_cost,roster.bid_cost,not roster.withdrawn,
       case when roster.owner_name is null then null else now() end,
       case when roster.withdrawn then now() else null end
from vt_sheet_roster roster
join public.cricket_teams team on team.code=roster.team_code
join public.players p on p.full_name=roster.player_name and p.team_id=team.id
left join public.league_members m
  on m.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'
 and m.display_name=roster.owner_name
 and m.status='active'
on conflict(league_id,player_id) do update
set owner_member_id=excluded.owner_member_id,
    acquisition_type=excluded.acquisition_type,
    acquisition_price=excluded.acquisition_price,
    bid_price=excluded.bid_price,
    active=excluded.active,
    acquired_at=excluded.acquired_at,
    released_at=excluded.released_at,
    updated_at=now();

delete from public.special_player_score_adjustments where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';
delete from public.member_match_scores x using public.fixtures f where f.id=x.fixture_id and f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';
delete from public.player_match_points x using public.fixtures f where f.id=x.fixture_id and f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';
delete from public.transfer_events where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';
delete from public.lineup_submissions where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';

update public.fixtures set
 status=case when match_number<=10 then 'completed' else 'scheduled' end,
 scoring_status=case when match_number<=10 then 'published' else 'pending' end,
 scorecard_source_url=case when match_number<=10 then 'https://www.espn.com/cricket/series/8048/scorecard/'||(1527673+match_number)::text else 'https://www.espn.com/cricket/series/8048/scores-fixtures' end,
 scheduled_start='2026-08-02 14:00:00+00'::timestamptz + match_number * interval '1 day',
 lineup_lock_at='2026-08-02 14:00:00+00'::timestamptz + match_number * interval '1 day',
 updated_at=now()
where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49';

alter table public.lineup_submissions disable trigger enforce_special_lineup_markers_before_write;

with resolved as (
 select v.*,m.id member_id,f.id fixture_id,cp.id captain_id,vp.id vice_id,ip.id impact_id,
        (select sum(cost) from vt_lineup_players cost_row where cost_row.owner_name=v.owner_name and cost_row.match_number=v.match_number) as lineup_cost,
        (select count(*)
         from vt_lineup_players borrowed_row
         join public.cricket_teams borrowed_team on borrowed_team.code=borrowed_row.team_code
         join public.players borrowed_player
           on borrowed_player.full_name=borrowed_row.player_name
          and borrowed_player.team_id=borrowed_team.id
         join public.league_players borrowed_league_player
           on borrowed_league_player.league_id=m.league_id
          and borrowed_league_player.player_id=borrowed_player.id
         where borrowed_row.owner_name=v.owner_name
           and borrowed_row.match_number=v.match_number
           and borrowed_league_player.owner_member_id is distinct from m.id) as borrowed_count
 from vt_lineups v
 join public.league_members m on m.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and m.display_name=v.owner_name and m.status='active'
 join public.fixtures f on f.league_id=m.league_id and f.match_number=v.match_number
 join lateral (
  select player.id
  from vt_lineup_players lineup_row
  join public.cricket_teams team on team.code=lineup_row.team_code
  join public.players player
    on player.full_name=lineup_row.player_name
   and player.team_id=team.id
  where lineup_row.owner_name=v.owner_name
    and lineup_row.match_number=v.match_number
    and lineup_row.player_name=v.captain_name
  limit 1
 ) cp on true
 join lateral (
  select player.id
  from vt_lineup_players lineup_row
  join public.cricket_teams team on team.code=lineup_row.team_code
  join public.players player
    on player.full_name=lineup_row.player_name
   and player.team_id=team.id
  where lineup_row.owner_name=v.owner_name
    and lineup_row.match_number=v.match_number
    and lineup_row.player_name=v.vice_captain_name
  limit 1
 ) vp on true
 left join lateral (
  select player.id
  from vt_lineup_players lineup_row
  join public.cricket_teams team on team.code=lineup_row.team_code
  join public.players player
    on player.full_name=lineup_row.player_name
   and player.team_id=team.id
  where lineup_row.owner_name=v.owner_name
    and lineup_row.match_number=v.match_number
    and lineup_row.player_name=v.impact_name
  limit 1
 ) ip on true
), one_per_lineup as (
 select distinct on (fixture_id,member_id) *
 from resolved
 order by fixture_id,member_id
)
insert into public.lineup_submissions(league_id,fixture_id,member_id,status,captain_player_id,vice_captain_player_id,impact_player_id,impact_type,lineup_cost,borrowed_player_count,submitted_at,locked_at,validation_status,validation_errors,validated_rule_set_id)
select '2fa606e1-2299-4c6d-9acf-348b7b858a49',fixture_id,member_id,'locked',captain_id,vice_id,impact_id,impact_type,
       lineup_cost,borrowed_count,f.lineup_lock_at-interval '1 hour',f.lineup_lock_at,'valid','[]'::jsonb,(select id from public.lineup_rule_sets where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and active limit 1)
from one_per_lineup r join public.fixtures f on f.id=r.fixture_id;

alter table public.lineup_submissions enable trigger enforce_special_lineup_markers_before_write;

insert into public.lineup_players(lineup_id,player_id,slot,is_borrowed)
select s.id,p.id,row_number() over(partition by s.id order by v.slot,v.player_name),(lp.owner_member_id is distinct from s.member_id)
from vt_lineup_players v
join public.league_members m on m.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and m.display_name=v.owner_name
join public.fixtures f on f.league_id=m.league_id and f.match_number=v.match_number
join public.lineup_submissions s on s.fixture_id=f.id and s.member_id=m.id
join lateral (
 select player.id
 from public.players player
 join public.cricket_teams team on team.id=player.team_id and team.code=v.team_code
 where player.full_name=v.player_name
 limit 1
) p on true
join public.league_players lp on lp.league_id=m.league_id and lp.player_id=p.id;

-- Match transfers are incoming players who were not in the owner's prior XI and
-- are not owned by that member. Match 1 is the free initial submission.
insert into public.transfer_events(
 league_id,member_id,fixture_id,player_in_id,stage,transfer_period_id,
 transfer_count,reason,created_by,created_at
)
select m.league_id,m.id,f.id,p.id,
       case when f.match_number>70 then 'playoff' else 'league' end,
       period.id,1,'lineup_change',auth.uid(),f.lineup_lock_at-interval '1 hour'
from vt_lineup_players current_row
join public.league_members m
  on m.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'
 and m.display_name=current_row.owner_name
 and m.status='active'
join public.fixtures f
  on f.league_id=m.league_id
 and f.match_number=current_row.match_number
join lateral (
 select player.id
 from public.players player
 join public.cricket_teams team on team.id=player.team_id and team.code=current_row.team_code
 where player.full_name=current_row.player_name
 limit 1
) p on true
join public.league_players owned
  on owned.league_id=m.league_id
 and owned.player_id=p.id
left join public.league_transfer_periods period
  on period.league_id=m.league_id
 and period.active
 and f.match_number between period.start_match_number and period.end_match_number
where current_row.match_number>1
  and owned.owner_member_id is distinct from m.id
  and not exists (
    select 1
    from vt_lineup_players prior_row
    where prior_row.owner_name=current_row.owner_name
      and prior_row.match_number=current_row.match_number-1
      and prior_row.player_name=current_row.player_name
      and prior_row.team_code=current_row.team_code
  );

insert into public.lineup_boosters(league_id,lineup_id,fixture_id,member_id,booster_rule_id,target_player_id)
select s.league_id,s.id,s.fixture_id,s.member_id,b.id,null
from vt_lineups v join public.league_members m on m.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and m.display_name=v.owner_name
join public.fixtures f on f.league_id=m.league_id and f.match_number=v.match_number
join public.lineup_submissions s on s.fixture_id=f.id and s.member_id=m.id
join public.booster_rules b on b.league_id=m.league_id and b.code=v.booster_code
where v.booster_code='2UP';

insert into public.player_match_points(fixture_id,player_id,rule_set_id,raw_stats,breakdown,batting_points,bowling_points,fielding_points,bonus_points,calculation_version,calculated_at,published_at)
select f.id,p.id,rs.id,
 jsonb_build_object('source','google_league_score_template','scorecard_url','https://www.espn.com/cricket/series/8048/scorecard/'||(1527673+v.match_number)::text,'player_name',v.player_name,'summary','Scorecard calculation verified against Cricbuzz / ESPNcricinfo'),
 jsonb_build_object('batting',v.batting,'bowling',v.bowling,'fielding',v.fielding,'bonus',v.total-v.batting-v.bowling-v.fielding,'detail','League scoring engine breakdown'),
 v.batting,v.bowling,v.fielding,v.total-v.batting-v.bowling-v.fielding,1,now(),now()
from vt_points v join public.fixtures f on f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and f.match_number=v.match_number
join lateral (
 select player.id
 from public.players player
 join public.cricket_teams team on team.id=player.team_id and team.code=v.team_code
 where player.full_name=v.player_name
 limit 1
) p on true
cross join lateral (select id from public.scoring_rule_sets where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and active limit 1) rs;

-- Rebuild the auditable per-player ROY ledger. Royalty is credited only when
-- another owner borrows the player and the owning member also selected that
-- player for the same match, matching publish_match_scores().
with royalty_values as (
 select
  s.league_id,s.fixture_id,special.id rule_set_id,lineup_player.player_id,
  s.member_id source_member_id,owner.owner_member_id recipient_member_id,
  exists (
   select 1 from public.effective_phase_special_players(f.phase_id,'marquee') marquee
   where marquee.member_id=owner.owner_member_id and marquee.player_id=lineup_player.player_id
  ) is_marquee,
  (
   case
    when s.impact_player_id=lineup_player.player_id and s.impact_type='BAI'
     then points.batting_points*rule.impact_multiplier
    when s.impact_player_id=lineup_player.player_id and s.impact_type='BOI'
     then points.bowling_points*rule.impact_multiplier
    else points.total_points
   end
   * case
      when s.captain_player_id=lineup_player.player_id then rule.captain_multiplier
      when s.vice_captain_player_id=lineup_player.player_id then rule.vice_captain_multiplier
      else 1
     end
   * case
      when booster.code='3X' and lineup_booster.target_player_id=lineup_player.player_id
       then booster.player_multiplier
      else 1
     end
   * case when booster.code='2UP' then coalesce(booster.match_multiplier,2) else 1 end
  )::numeric final_contribution,
  special.regular_royalty_percent,special.marquee_royalty_percent,
  special.regular_minimum_royalty,special.marquee_minimum_royalty,
  special.royalty_zero_floor,special.royalty_rounding
 from public.lineup_submissions s
 join public.fixtures f on f.id=s.fixture_id
 join public.lineup_players lineup_player on lineup_player.lineup_id=s.id
 join public.player_match_points points
  on points.fixture_id=s.fixture_id and points.player_id=lineup_player.player_id
 and points.calculation_version=(
  select max(latest.calculation_version) from public.player_match_points latest
  where latest.fixture_id=s.fixture_id
 )
 join public.league_players owner
  on owner.league_id=s.league_id and owner.player_id=lineup_player.player_id
 join public.lineup_rule_sets rule on rule.id=public.lineup_rule_set_for_fixture(s.fixture_id)
 join lateral public.special_player_rules_for_match(s.league_id,f.match_number) special on true
 left join public.lineup_boosters lineup_booster on lineup_booster.lineup_id=s.id
 left join public.booster_rules booster on booster.id=lineup_booster.booster_rule_id
 where s.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49'
  and f.match_number between 1 and 10
  and s.status in ('submitted','locked')
  and owner.owner_member_id is not null
  and owner.owner_member_id<>s.member_id
  and coalesce(special.marquee_mode_enabled,false)
  and exists (
   select 1
   from public.lineup_submissions owner_lineup
   join public.lineup_players owner_player on owner_player.lineup_id=owner_lineup.id
   where owner_lineup.fixture_id=s.fixture_id
    and owner_lineup.member_id=owner.owner_member_id
    and owner_lineup.status in ('submitted','locked')
    and owner_player.player_id=lineup_player.player_id
  )
)
insert into public.special_player_score_adjustments(
 league_id,fixture_id,rule_set_id,player_id,source_member_id,recipient_member_id,
 adjustment_type,final_player_contribution,rate_percent,minimum_fee,
 adjustment_points,calculation_breakdown
)
select
 league_id,fixture_id,rule_set_id,player_id,source_member_id,recipient_member_id,
 case when is_marquee then 'marquee_royalty' else 'regular_royalty' end,
 final_contribution,
 case when is_marquee then marquee_royalty_percent else regular_royalty_percent end,
 case when is_marquee then marquee_minimum_royalty else regular_minimum_royalty end,
 public.special_royalty_points(
  final_contribution,
  case when is_marquee then marquee_royalty_percent else regular_royalty_percent end,
  case when is_marquee then marquee_minimum_royalty else regular_minimum_royalty end,
  royalty_zero_floor,royalty_rounding
 ),
 jsonb_build_object(
  'zero_floor',royalty_zero_floor,'rounding',royalty_rounding,
  'is_marquee',is_marquee,'owner_selected_player',true,'source','volume_test_backfill'
 )
from royalty_values;

insert into public.member_match_scores(fixture_id,member_id,lineup_id,base_points,captain_bonus,vice_captain_bonus,impact_adjustment,ownership_adjustment,rank,published_at,calculation_breakdown,special_rule_set_id)
select f.id,m.id,s.id,v.total,0,0,0,0,
 dense_rank() over(partition by f.id order by v.total desc),now(),
 jsonb_build_object('source','Google Sheet League tab','sheet_total',v.total,'note','Historical volume-test total includes markers, royalty and sheet booster calculations'),
 (select id from public.special_player_rule_sets where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and active order by version desc limit 1)
from vt_owner_scores v join public.league_members m on m.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and m.display_name=v.owner_name
join public.fixtures f on f.league_id=m.league_id and f.match_number=v.match_number
join public.lineup_submissions s on s.fixture_id=f.id and s.member_id=m.id;

insert into public.audit_events(league_id,actor_user_id,action,entity_type,entity_id,after_data)
values('2fa606e1-2299-4c6d-9acf-348b7b858a49',auth.uid(),'volume_test_matches_1_10_loaded','league','2fa606e1-2299-4c6d-9acf-348b7b858a49',
 jsonb_build_object('lineups',90,'lineup_players',990,'published_matches',10,'next_match',11,'next_start_ist','2026-08-13 19:30','source_sheet','1N7KS_j4BFWP-C95TB9DgR0x251OnyKedzZtjQ6XH72w'));

do $$
begin
 if (select count(*) from public.lineup_submissions where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and status='locked')<>90 then raise exception 'Lineup count mismatch'; end if;
 if (select count(*) from public.lineup_players x join public.lineup_submissions s on s.id=x.lineup_id where s.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49')<>990 then raise exception 'Lineup player count mismatch'; end if;
 if (select count(*) from public.member_match_scores x join public.fixtures f on f.id=x.fixture_id where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49')<>90 then raise exception 'Member score count mismatch'; end if;
 if (select count(*) from public.special_player_score_adjustments where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and adjustment_type in ('regular_royalty','marquee_royalty'))=0 then raise exception 'Royalty adjustment ledger is empty'; end if;
 if (select count(*) from public.fixtures where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and match_number<=10 and scoring_status='published')<>10 then raise exception 'Published fixture mismatch'; end if;
end $$;

select 'ready' status,
 (select count(*) from public.lineup_submissions where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49') lineups,
 (select count(*) from public.lineup_players x join public.lineup_submissions s on s.id=x.lineup_id where s.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49') lineup_players,
 (select count(*) from public.player_match_points x join public.fixtures f on f.id=x.fixture_id where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49') player_points,
 (select count(*) from public.member_match_scores x join public.fixtures f on f.id=x.fixture_id where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49') member_scores,
 (select count(*) from public.special_player_score_adjustments where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and adjustment_type in ('regular_royalty','marquee_royalty')) royalty_rows,
 (select count(*) from public.volume_test_match_backup where league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49') backups;
commit;

-- Read-only post-run audit:
-- select f.match_number,f.status,f.scoring_status,
--        to_char(f.scheduled_start at time zone 'Asia/Kolkata','YYYY-MM-DD HH24:MI') start_ist,
--        count(distinct s.id) lineups,count(distinct ms.id) scores
-- from public.fixtures f
-- left join public.lineup_submissions s on s.fixture_id=f.id
-- left join public.member_match_scores ms on ms.fixture_id=f.id
-- where f.league_id='2fa606e1-2299-4c6d-9acf-348b7b858a49' and f.match_number<=11
-- group by f.id order by f.match_number;
